function out = jac_sig_r_tl(r_n,r_e,r_d,v,gamma,xi,w_e,w_n,w_d,terr_dis,p1_e,p1_h,p2_h,p3_h,p1_n,phi_max,delta_r0,g,k_r)
%JAC_SIG_R_TL
%    OUT = JAC_SIG_R_TL(R_N,R_E,R_D,V,GAMMA,XI,W_E,W_N,W_D,TERR_DIS,P1_E,P1_H,P2_H,P3_H,P1_N,PHI_MAX,DELTA_R0,G,K_R)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    30-Sep-2019 03:40:26

t2 = p2_h-p3_h;
t3 = cos(gamma);
t4 = cos(xi);
t5 = t3.*t4.*v;
t6 = t5+w_n;
t7 = sin(xi);
t8 = t3.*t7.*v;
t9 = t8+w_e;
t10 = sin(gamma);
t13 = t10.*v;
t11 = -t13+w_d;
t12 = terr_dis.^2;
t14 = t2.*t6.*terr_dis;
t15 = p1_h-p2_h;
t16 = t9.*t15.*terr_dis;
t25 = t11.*t12;
t17 = t14+t16-t25;
t18 = 1.0./t17;
t19 = t6.^2;
t20 = t9.^2;
t21 = t11.^2;
t22 = t19+t20+t21;
t23 = sqrt(t22);
t26 = p1_h+r_d;
t27 = t12.*t26;
t28 = p1_e-r_e;
t29 = t15.*t28.*terr_dis;
t30 = p1_n-r_n;
t31 = t2.*t30.*terr_dis;
t32 = t27+t29+t31;
t33 = t18.*t23.*t32;
t34 = 1.0./g;
t35 = tan(phi_max);
t36 = 1.0./t35;
t37 = k_r.*t22.*t34.*t36;
t24 = delta_r0-t33+t37;
t38 = t24.^2;
t39 = t3.*t4.*t6.*2.0;
t40 = t3.*t7.*t9.*2.0;
t41 = t39+t40-t10.*t11.*2.0;
t42 = 1.0./t17.^2;
t43 = t3.*t11.*v.*2.0;
t44 = t4.*t6.*t10.*v.*2.0;
t45 = t7.*t9.*t10.*v.*2.0;
t46 = t43+t44+t45;
t47 = 1.0./sqrt(t22);
t48 = t3.*t4.*t9.*v.*2.0;
t49 = t48-t3.*t6.*t7.*v.*2.0;
out = [t2.*t18.*t23.*t38.*terr_dis.*-3.0,t15.*t18.*t23.*t38.*terr_dis.*-3.0,t12.*t18.*t23.*t38.*3.0,t38.*(k_r.*t34.*t36.*t41-t18.*t32.*t41.*t47.*(1.0./2.0)+t23.*t32.*t42.*(t10.*t12+t2.*t3.*t4.*terr_dis+t3.*t7.*t15.*terr_dis)).*-3.0,t38.*(t23.*t32.*t42.*(-t3.*t12.*v+t2.*t4.*t10.*terr_dis.*v+t7.*t10.*t15.*terr_dis.*v)+k_r.*t34.*t36.*t46-t18.*t32.*t46.*t47.*(1.0./2.0)).*3.0,t38.*(-k_r.*t34.*t36.*t49+t18.*t32.*t47.*t49.*(1.0./2.0)+t23.*t32.*t42.*(t2.*t3.*t7.*terr_dis.*v-t3.*t4.*t15.*terr_dis.*v)).*3.0];
