function out = jac_sig_r_tl(r_n,r_e,r_d,v,gamma,xi,w_e,w_n,terr_dis,p1_e,p1_h,p2_h,p3_h,p1_n,phi_max,delta_r0,g,k_r)
%JAC_SIG_R_TL
%    OUT = JAC_SIG_R_TL(R_N,R_E,R_D,V,GAMMA,XI,W_E,W_N,TERR_DIS,P1_E,P1_H,P2_H,P3_H,P1_N,PHI_MAX,DELTA_R0,G,K_R)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    26-Sep-2019 10:55:00

t3 = cos(gamma);
t5 = cos(xi);
t6 = t3.*t5.*v;
t2 = t6+w_n;
t8 = sin(xi);
t9 = t3.*t8.*v;
t4 = t9+w_e;
t7 = p2_h-p3_h;
t10 = t2.^2;
t11 = t4.^2;
t12 = t10+t11;
t13 = sqrt(t12);
t14 = t2.*t7.*terr_dis;
t15 = p1_h-p2_h;
t16 = t4.*t15.*terr_dis;
t17 = t14+t16;
t18 = 1.0./t17;
t20 = terr_dis.^2;
t21 = p1_h+r_d;
t22 = t20.*t21;
t23 = p1_e-r_e;
t24 = t15.*t23.*terr_dis;
t25 = p1_n-r_n;
t26 = t7.*t25.*terr_dis;
t27 = t22+t24+t26;
t28 = t13.*t18.*t27;
t29 = 1.0./g;
t30 = tan(phi_max);
t31 = 1.0./t30;
t32 = k_r.*t12.*t29.*t31;
t19 = delta_r0-t28+t32;
t33 = t19.^2;
t34 = t2.*t3.*t5.*2.0;
t35 = t3.*t4.*t8.*2.0;
t36 = t34+t35;
t37 = sin(gamma);
t38 = t2.*t5.*t37.*v.*2.0;
t39 = t4.*t8.*t37.*v.*2.0;
t40 = t38+t39;
t41 = 1.0./sqrt(t12);
t42 = 1.0./t17.^2;
t43 = t3.*t4.*t5.*v.*2.0;
t44 = t43-t2.*t3.*t8.*v.*2.0;
out = [t7.*t13.*t18.*t33.*terr_dis.*-3.0,t13.*t15.*t18.*t33.*terr_dis.*-3.0,t13.*t18.*t20.*t33.*3.0,t33.*(k_r.*t29.*t31.*t36-t18.*t27.*t36.*t41.*(1.0./2.0)+t13.*t27.*t42.*(t3.*t5.*t7.*terr_dis+t3.*t8.*t15.*terr_dis)).*-3.0,t33.*(k_r.*t29.*t31.*t40-t18.*t27.*t40.*t41.*(1.0./2.0)+t13.*t27.*t42.*(t5.*t7.*t37.*terr_dis.*v+t8.*t15.*t37.*terr_dis.*v)).*3.0,t33.*(-k_r.*t29.*t31.*t44+t18.*t27.*t41.*t44.*(1.0./2.0)+t13.*t27.*t42.*(t3.*t7.*t8.*terr_dis.*v-t3.*t5.*t15.*terr_dis.*v)).*3.0];
