function out = jac_r(n_occ_e,n_occ_h,n_occ_n,v_ray_e,v_ray_h,v_ray_n)
%JAC_R
%    OUT = JAC_R(N_OCC_E,N_OCC_H,N_OCC_N,V_RAY_E,V_RAY_H,V_RAY_N)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    07-Feb-2020 17:02:40

t2 = n_occ_e.*v_ray_e;
t3 = n_occ_h.*v_ray_h;
t4 = n_occ_n.*v_ray_n;
t5 = t2+t3+t4;
t6 = 1.0./t5;
out = [-n_occ_n.*t6,-n_occ_e.*t6,n_occ_h.*t6,0.0,0.0,0.0];
