function out = jac_h(de,delta_y,h1,h12,h2,h3,h34,h4,sgn_e,sgn_n,terr_dis,xi)
%JAC_H
%    OUT = JAC_H(DE,DELTA_Y,H1,H12,H2,H3,H34,H4,SGN_E,SGN_N,TERR_DIS,XI)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    07-Feb-2020 17:06:43

t2 = 1.0./terr_dis;
t3 = de-1.0;
t4 = cos(xi);
t5 = sin(xi);
out = [de.*(h3.*t2-h4.*t2)-t3.*(h1.*t2-h2.*t2),t2.*(h12-h34),-1.0,de.*(delta_y.*h3.*sgn_n.*t2.*t4-delta_y.*h4.*sgn_n.*t2.*t4)-t3.*(delta_y.*h1.*sgn_n.*t2.*t4-delta_y.*h2.*sgn_n.*t2.*t4)-delta_y.*h12.*sgn_e.*t2.*t5+delta_y.*h34.*sgn_e.*t2.*t5];
