/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *    
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2014 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov, Rien Quirynen, KU Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC)
 *    under supervision of Moritz Diehl. All rights reserved.
 *    
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *    
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *    
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *    
 */


#include "acado_common.h"




/******************************************************************************/
/*                                                                            */
/* ACADO code generation                                                      */
/*                                                                            */
/******************************************************************************/


int modelSimulation(  )
{
int ret;

int lRun1;
ret = 0;
for (lRun1 = 0; lRun1 < 10; ++lRun1)
{
acadoWorkspace.state[0] = acadoVariables.x[lRun1];

acadoWorkspace.state[3] = acadoVariables.u[lRun1];

ret = integrate(acadoWorkspace.state, 1);

acadoWorkspace.d[lRun1] = acadoWorkspace.state[0] - acadoVariables.x[lRun1 + 1];

acadoWorkspace.evGx[lRun1] = acadoWorkspace.state[1];

acadoWorkspace.evGu[lRun1] = acadoWorkspace.state[2];
}
return ret;
}

void evaluateLSQ(const real_t* in, real_t* out)
{
const real_t* xd = in;
const real_t* u = in + 1;

/* Compute outputs: */
out[0] = xd[0];
out[1] = u[0];
}

void evaluateLSQEndTerm(const real_t* in, real_t* out)
{
const real_t* xd = in;

/* Compute outputs: */
out[0] = xd[0];
}

void setObjQ1Q2( real_t* const tmpObjS, real_t* const tmpQ1, real_t* const tmpQ2 )
{
tmpQ2[0] = +tmpObjS[0];
tmpQ2[1] = +tmpObjS[1];
tmpQ1[0] = + tmpQ2[0];
}

void setObjR1R2( real_t* const tmpObjS, real_t* const tmpR1, real_t* const tmpR2 )
{
tmpR2[0] = +tmpObjS[2];
tmpR2[1] = +tmpObjS[3];
tmpR1[0] = + tmpR2[1];
}

void setObjQN1QN2( real_t* const tmpObjSEndTerm, real_t* const tmpQN1, real_t* const tmpQN2 )
{
tmpQN2[0] = +tmpObjSEndTerm[0];
tmpQN1[0] = + tmpQN2[0];
}

void evaluateObjective(  )
{
int runObj;
for (runObj = 0; runObj < 10; ++runObj)
{
acadoWorkspace.objValueIn[0] = acadoVariables.x[runObj];
acadoWorkspace.objValueIn[1] = acadoVariables.u[runObj];

evaluateLSQ( acadoWorkspace.objValueIn, acadoWorkspace.objValueOut );
acadoWorkspace.Dy[runObj * 2] = acadoWorkspace.objValueOut[0];
acadoWorkspace.Dy[runObj * 2 + 1] = acadoWorkspace.objValueOut[1];

setObjQ1Q2( acadoVariables.W, &(acadoWorkspace.Q1[ runObj ]), &(acadoWorkspace.Q2[ runObj * 2 ]) );

setObjR1R2( acadoVariables.W, &(acadoWorkspace.R1[ runObj ]), &(acadoWorkspace.R2[ runObj * 2 ]) );

}
acadoWorkspace.objValueIn[0] = acadoVariables.x[10];
evaluateLSQEndTerm( acadoWorkspace.objValueIn, acadoWorkspace.objValueOut );

acadoWorkspace.DyN[0] = acadoWorkspace.objValueOut[0];

setObjQN1QN2( acadoVariables.WN, acadoWorkspace.QN1, acadoWorkspace.QN2 );

}

void multGxd( real_t* const dOld, real_t* const Gx1, real_t* const dNew )
{
dNew[0] += + Gx1[0]*dOld[0];
}

void moveGxT( real_t* const Gx1, real_t* const Gx2 )
{
Gx2[0] = Gx1[0];
}

void multGxGx( real_t* const Gx1, real_t* const Gx2, real_t* const Gx3 )
{
Gx3[0] = + Gx1[0]*Gx2[0];
}

void multGxGu( real_t* const Gx1, real_t* const Gu1, real_t* const Gu2 )
{
Gu2[0] = + Gx1[0]*Gu1[0];
}

void moveGuE( real_t* const Gu1, real_t* const Gu2 )
{
Gu2[0] = Gu1[0];
}

void setBlockH11( int iRow, int iCol, real_t* const Gu1, real_t* const Gu2 )
{
acadoWorkspace.H[(iRow * 10) + (iCol)] += + Gu1[0]*Gu2[0];
}

void setBlockH11_R1( int iRow, int iCol, real_t* const R11 )
{
acadoWorkspace.H[(iRow * 10) + (iCol)] = R11[0] + (real_t)1.0000000000000000e-10;
}

void zeroBlockH11( int iRow, int iCol )
{
acadoWorkspace.H[(iRow * 10) + (iCol)] = 0.0000000000000000e+00;
}

void copyHTH( int iRow, int iCol )
{
acadoWorkspace.H[(iRow * 10) + (iCol)] = acadoWorkspace.H[(iCol * 10) + (iRow)];
}

void multQ1d( real_t* const Gx1, real_t* const dOld, real_t* const dNew )
{
dNew[0] = + Gx1[0]*dOld[0];
}

void multQN1d( real_t* const QN1, real_t* const dOld, real_t* const dNew )
{
dNew[0] = + acadoWorkspace.QN1[0]*dOld[0];
}

void multRDy( real_t* const R2, real_t* const Dy1, real_t* const RDy1 )
{
RDy1[0] = + R2[0]*Dy1[0] + R2[1]*Dy1[1];
}

void multQDy( real_t* const Q2, real_t* const Dy1, real_t* const QDy1 )
{
QDy1[0] = + Q2[0]*Dy1[0] + Q2[1]*Dy1[1];
}

void multEQDy( real_t* const E1, real_t* const QDy1, real_t* const U1 )
{
U1[0] += + E1[0]*QDy1[0];
}

void multQETGx( real_t* const E1, real_t* const Gx1, real_t* const H101 )
{
H101[0] += + E1[0]*Gx1[0];
}

void zeroBlockH10( real_t* const H101 )
{
H101[0] = 0.0000000000000000e+00;
}

void multEDu( real_t* const E1, real_t* const U1, real_t* const dNew )
{
dNew[0] += + E1[0]*U1[0];
}

void macETSlu( real_t* const E0, real_t* const g1 )
{
g1[0] += 0.0;
;
}

void condensePrep(  )
{
moveGuE( acadoWorkspace.evGu, acadoWorkspace.E );
moveGxT( &(acadoWorkspace.evGx[ 1 ]), acadoWorkspace.T );
multGxd( acadoWorkspace.d, &(acadoWorkspace.evGx[ 1 ]), &(acadoWorkspace.d[ 1 ]) );
multGxGx( acadoWorkspace.T, acadoWorkspace.evGx, &(acadoWorkspace.evGx[ 1 ]) );

multGxGu( acadoWorkspace.T, acadoWorkspace.E, &(acadoWorkspace.E[ 1 ]) );

moveGuE( &(acadoWorkspace.evGu[ 1 ]), &(acadoWorkspace.E[ 2 ]) );

moveGxT( &(acadoWorkspace.evGx[ 2 ]), acadoWorkspace.T );
multGxd( &(acadoWorkspace.d[ 1 ]), &(acadoWorkspace.evGx[ 2 ]), &(acadoWorkspace.d[ 2 ]) );
multGxGx( acadoWorkspace.T, &(acadoWorkspace.evGx[ 1 ]), &(acadoWorkspace.evGx[ 2 ]) );

multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 1 ]), &(acadoWorkspace.E[ 3 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 2 ]), &(acadoWorkspace.E[ 4 ]) );

moveGuE( &(acadoWorkspace.evGu[ 2 ]), &(acadoWorkspace.E[ 5 ]) );

moveGxT( &(acadoWorkspace.evGx[ 3 ]), acadoWorkspace.T );
multGxd( &(acadoWorkspace.d[ 2 ]), &(acadoWorkspace.evGx[ 3 ]), &(acadoWorkspace.d[ 3 ]) );
multGxGx( acadoWorkspace.T, &(acadoWorkspace.evGx[ 2 ]), &(acadoWorkspace.evGx[ 3 ]) );

multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 3 ]), &(acadoWorkspace.E[ 6 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 4 ]), &(acadoWorkspace.E[ 7 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 5 ]), &(acadoWorkspace.E[ 8 ]) );

moveGuE( &(acadoWorkspace.evGu[ 3 ]), &(acadoWorkspace.E[ 9 ]) );

moveGxT( &(acadoWorkspace.evGx[ 4 ]), acadoWorkspace.T );
multGxd( &(acadoWorkspace.d[ 3 ]), &(acadoWorkspace.evGx[ 4 ]), &(acadoWorkspace.d[ 4 ]) );
multGxGx( acadoWorkspace.T, &(acadoWorkspace.evGx[ 3 ]), &(acadoWorkspace.evGx[ 4 ]) );

multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 6 ]), &(acadoWorkspace.E[ 10 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 7 ]), &(acadoWorkspace.E[ 11 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 8 ]), &(acadoWorkspace.E[ 12 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 9 ]), &(acadoWorkspace.E[ 13 ]) );

moveGuE( &(acadoWorkspace.evGu[ 4 ]), &(acadoWorkspace.E[ 14 ]) );

moveGxT( &(acadoWorkspace.evGx[ 5 ]), acadoWorkspace.T );
multGxd( &(acadoWorkspace.d[ 4 ]), &(acadoWorkspace.evGx[ 5 ]), &(acadoWorkspace.d[ 5 ]) );
multGxGx( acadoWorkspace.T, &(acadoWorkspace.evGx[ 4 ]), &(acadoWorkspace.evGx[ 5 ]) );

multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 10 ]), &(acadoWorkspace.E[ 15 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 11 ]), &(acadoWorkspace.E[ 16 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 12 ]), &(acadoWorkspace.E[ 17 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 13 ]), &(acadoWorkspace.E[ 18 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 14 ]), &(acadoWorkspace.E[ 19 ]) );

moveGuE( &(acadoWorkspace.evGu[ 5 ]), &(acadoWorkspace.E[ 20 ]) );

moveGxT( &(acadoWorkspace.evGx[ 6 ]), acadoWorkspace.T );
multGxd( &(acadoWorkspace.d[ 5 ]), &(acadoWorkspace.evGx[ 6 ]), &(acadoWorkspace.d[ 6 ]) );
multGxGx( acadoWorkspace.T, &(acadoWorkspace.evGx[ 5 ]), &(acadoWorkspace.evGx[ 6 ]) );

multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.E[ 21 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.E[ 22 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 17 ]), &(acadoWorkspace.E[ 23 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 18 ]), &(acadoWorkspace.E[ 24 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 19 ]), &(acadoWorkspace.E[ 25 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 20 ]), &(acadoWorkspace.E[ 26 ]) );

moveGuE( &(acadoWorkspace.evGu[ 6 ]), &(acadoWorkspace.E[ 27 ]) );

moveGxT( &(acadoWorkspace.evGx[ 7 ]), acadoWorkspace.T );
multGxd( &(acadoWorkspace.d[ 6 ]), &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.d[ 7 ]) );
multGxGx( acadoWorkspace.T, &(acadoWorkspace.evGx[ 6 ]), &(acadoWorkspace.evGx[ 7 ]) );

multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.E[ 28 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.E[ 29 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.E[ 30 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 24 ]), &(acadoWorkspace.E[ 31 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 25 ]), &(acadoWorkspace.E[ 32 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 26 ]), &(acadoWorkspace.E[ 33 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 27 ]), &(acadoWorkspace.E[ 34 ]) );

moveGuE( &(acadoWorkspace.evGu[ 7 ]), &(acadoWorkspace.E[ 35 ]) );

moveGxT( &(acadoWorkspace.evGx[ 8 ]), acadoWorkspace.T );
multGxd( &(acadoWorkspace.d[ 7 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.d[ 8 ]) );
multGxGx( acadoWorkspace.T, &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.evGx[ 8 ]) );

multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.E[ 36 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.E[ 37 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.E[ 38 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.E[ 39 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 32 ]), &(acadoWorkspace.E[ 40 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 33 ]), &(acadoWorkspace.E[ 41 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 34 ]), &(acadoWorkspace.E[ 42 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 35 ]), &(acadoWorkspace.E[ 43 ]) );

moveGuE( &(acadoWorkspace.evGu[ 8 ]), &(acadoWorkspace.E[ 44 ]) );

moveGxT( &(acadoWorkspace.evGx[ 9 ]), acadoWorkspace.T );
multGxd( &(acadoWorkspace.d[ 8 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.d[ 9 ]) );
multGxGx( acadoWorkspace.T, &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.evGx[ 9 ]) );

multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.E[ 45 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.E[ 46 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.E[ 47 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.E[ 48 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.E[ 49 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 41 ]), &(acadoWorkspace.E[ 50 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 42 ]), &(acadoWorkspace.E[ 51 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 43 ]), &(acadoWorkspace.E[ 52 ]) );
multGxGu( acadoWorkspace.T, &(acadoWorkspace.E[ 44 ]), &(acadoWorkspace.E[ 53 ]) );

moveGuE( &(acadoWorkspace.evGu[ 9 ]), &(acadoWorkspace.E[ 54 ]) );

multGxGu( &(acadoWorkspace.Q1[ 1 ]), acadoWorkspace.E, acadoWorkspace.QE );
multGxGu( &(acadoWorkspace.Q1[ 2 ]), &(acadoWorkspace.E[ 1 ]), &(acadoWorkspace.QE[ 1 ]) );
multGxGu( &(acadoWorkspace.Q1[ 2 ]), &(acadoWorkspace.E[ 2 ]), &(acadoWorkspace.QE[ 2 ]) );
multGxGu( &(acadoWorkspace.Q1[ 3 ]), &(acadoWorkspace.E[ 3 ]), &(acadoWorkspace.QE[ 3 ]) );
multGxGu( &(acadoWorkspace.Q1[ 3 ]), &(acadoWorkspace.E[ 4 ]), &(acadoWorkspace.QE[ 4 ]) );
multGxGu( &(acadoWorkspace.Q1[ 3 ]), &(acadoWorkspace.E[ 5 ]), &(acadoWorkspace.QE[ 5 ]) );
multGxGu( &(acadoWorkspace.Q1[ 4 ]), &(acadoWorkspace.E[ 6 ]), &(acadoWorkspace.QE[ 6 ]) );
multGxGu( &(acadoWorkspace.Q1[ 4 ]), &(acadoWorkspace.E[ 7 ]), &(acadoWorkspace.QE[ 7 ]) );
multGxGu( &(acadoWorkspace.Q1[ 4 ]), &(acadoWorkspace.E[ 8 ]), &(acadoWorkspace.QE[ 8 ]) );
multGxGu( &(acadoWorkspace.Q1[ 4 ]), &(acadoWorkspace.E[ 9 ]), &(acadoWorkspace.QE[ 9 ]) );
multGxGu( &(acadoWorkspace.Q1[ 5 ]), &(acadoWorkspace.E[ 10 ]), &(acadoWorkspace.QE[ 10 ]) );
multGxGu( &(acadoWorkspace.Q1[ 5 ]), &(acadoWorkspace.E[ 11 ]), &(acadoWorkspace.QE[ 11 ]) );
multGxGu( &(acadoWorkspace.Q1[ 5 ]), &(acadoWorkspace.E[ 12 ]), &(acadoWorkspace.QE[ 12 ]) );
multGxGu( &(acadoWorkspace.Q1[ 5 ]), &(acadoWorkspace.E[ 13 ]), &(acadoWorkspace.QE[ 13 ]) );
multGxGu( &(acadoWorkspace.Q1[ 5 ]), &(acadoWorkspace.E[ 14 ]), &(acadoWorkspace.QE[ 14 ]) );
multGxGu( &(acadoWorkspace.Q1[ 6 ]), &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.QE[ 15 ]) );
multGxGu( &(acadoWorkspace.Q1[ 6 ]), &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.QE[ 16 ]) );
multGxGu( &(acadoWorkspace.Q1[ 6 ]), &(acadoWorkspace.E[ 17 ]), &(acadoWorkspace.QE[ 17 ]) );
multGxGu( &(acadoWorkspace.Q1[ 6 ]), &(acadoWorkspace.E[ 18 ]), &(acadoWorkspace.QE[ 18 ]) );
multGxGu( &(acadoWorkspace.Q1[ 6 ]), &(acadoWorkspace.E[ 19 ]), &(acadoWorkspace.QE[ 19 ]) );
multGxGu( &(acadoWorkspace.Q1[ 6 ]), &(acadoWorkspace.E[ 20 ]), &(acadoWorkspace.QE[ 20 ]) );
multGxGu( &(acadoWorkspace.Q1[ 7 ]), &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QE[ 21 ]) );
multGxGu( &(acadoWorkspace.Q1[ 7 ]), &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.QE[ 22 ]) );
multGxGu( &(acadoWorkspace.Q1[ 7 ]), &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.QE[ 23 ]) );
multGxGu( &(acadoWorkspace.Q1[ 7 ]), &(acadoWorkspace.E[ 24 ]), &(acadoWorkspace.QE[ 24 ]) );
multGxGu( &(acadoWorkspace.Q1[ 7 ]), &(acadoWorkspace.E[ 25 ]), &(acadoWorkspace.QE[ 25 ]) );
multGxGu( &(acadoWorkspace.Q1[ 7 ]), &(acadoWorkspace.E[ 26 ]), &(acadoWorkspace.QE[ 26 ]) );
multGxGu( &(acadoWorkspace.Q1[ 7 ]), &(acadoWorkspace.E[ 27 ]), &(acadoWorkspace.QE[ 27 ]) );
multGxGu( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 28 ]) );
multGxGu( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QE[ 29 ]) );
multGxGu( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.QE[ 30 ]) );
multGxGu( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.QE[ 31 ]) );
multGxGu( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.E[ 32 ]), &(acadoWorkspace.QE[ 32 ]) );
multGxGu( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.E[ 33 ]), &(acadoWorkspace.QE[ 33 ]) );
multGxGu( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.E[ 34 ]), &(acadoWorkspace.QE[ 34 ]) );
multGxGu( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.E[ 35 ]), &(acadoWorkspace.QE[ 35 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 36 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 37 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QE[ 38 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.QE[ 39 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.QE[ 40 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 41 ]), &(acadoWorkspace.QE[ 41 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 42 ]), &(acadoWorkspace.QE[ 42 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 43 ]), &(acadoWorkspace.QE[ 43 ]) );
multGxGu( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.E[ 44 ]), &(acadoWorkspace.QE[ 44 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 45 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 46 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 47 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QE[ 48 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.QE[ 49 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 50 ]), &(acadoWorkspace.QE[ 50 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 51 ]), &(acadoWorkspace.QE[ 51 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 52 ]), &(acadoWorkspace.QE[ 52 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 53 ]), &(acadoWorkspace.QE[ 53 ]) );
multGxGu( acadoWorkspace.QN1, &(acadoWorkspace.E[ 54 ]), &(acadoWorkspace.QE[ 54 ]) );

zeroBlockH10( acadoWorkspace.H10 );
multQETGx( acadoWorkspace.QE, acadoWorkspace.evGx, acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 1 ]), &(acadoWorkspace.evGx[ 1 ]), acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 3 ]), &(acadoWorkspace.evGx[ 2 ]), acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 6 ]), &(acadoWorkspace.evGx[ 3 ]), acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 10 ]), &(acadoWorkspace.evGx[ 4 ]), acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 15 ]), &(acadoWorkspace.evGx[ 5 ]), acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 21 ]), &(acadoWorkspace.evGx[ 6 ]), acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 28 ]), &(acadoWorkspace.evGx[ 7 ]), acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 36 ]), &(acadoWorkspace.evGx[ 8 ]), acadoWorkspace.H10 );
multQETGx( &(acadoWorkspace.QE[ 45 ]), &(acadoWorkspace.evGx[ 9 ]), acadoWorkspace.H10 );
zeroBlockH10( &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 2 ]), &(acadoWorkspace.evGx[ 1 ]), &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 4 ]), &(acadoWorkspace.evGx[ 2 ]), &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 7 ]), &(acadoWorkspace.evGx[ 3 ]), &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 11 ]), &(acadoWorkspace.evGx[ 4 ]), &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 16 ]), &(acadoWorkspace.evGx[ 5 ]), &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 22 ]), &(acadoWorkspace.evGx[ 6 ]), &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 29 ]), &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 37 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.H10[ 1 ]) );
multQETGx( &(acadoWorkspace.QE[ 46 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 1 ]) );
zeroBlockH10( &(acadoWorkspace.H10[ 2 ]) );
multQETGx( &(acadoWorkspace.QE[ 5 ]), &(acadoWorkspace.evGx[ 2 ]), &(acadoWorkspace.H10[ 2 ]) );
multQETGx( &(acadoWorkspace.QE[ 8 ]), &(acadoWorkspace.evGx[ 3 ]), &(acadoWorkspace.H10[ 2 ]) );
multQETGx( &(acadoWorkspace.QE[ 12 ]), &(acadoWorkspace.evGx[ 4 ]), &(acadoWorkspace.H10[ 2 ]) );
multQETGx( &(acadoWorkspace.QE[ 17 ]), &(acadoWorkspace.evGx[ 5 ]), &(acadoWorkspace.H10[ 2 ]) );
multQETGx( &(acadoWorkspace.QE[ 23 ]), &(acadoWorkspace.evGx[ 6 ]), &(acadoWorkspace.H10[ 2 ]) );
multQETGx( &(acadoWorkspace.QE[ 30 ]), &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.H10[ 2 ]) );
multQETGx( &(acadoWorkspace.QE[ 38 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.H10[ 2 ]) );
multQETGx( &(acadoWorkspace.QE[ 47 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 2 ]) );
zeroBlockH10( &(acadoWorkspace.H10[ 3 ]) );
multQETGx( &(acadoWorkspace.QE[ 9 ]), &(acadoWorkspace.evGx[ 3 ]), &(acadoWorkspace.H10[ 3 ]) );
multQETGx( &(acadoWorkspace.QE[ 13 ]), &(acadoWorkspace.evGx[ 4 ]), &(acadoWorkspace.H10[ 3 ]) );
multQETGx( &(acadoWorkspace.QE[ 18 ]), &(acadoWorkspace.evGx[ 5 ]), &(acadoWorkspace.H10[ 3 ]) );
multQETGx( &(acadoWorkspace.QE[ 24 ]), &(acadoWorkspace.evGx[ 6 ]), &(acadoWorkspace.H10[ 3 ]) );
multQETGx( &(acadoWorkspace.QE[ 31 ]), &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.H10[ 3 ]) );
multQETGx( &(acadoWorkspace.QE[ 39 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.H10[ 3 ]) );
multQETGx( &(acadoWorkspace.QE[ 48 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 3 ]) );
zeroBlockH10( &(acadoWorkspace.H10[ 4 ]) );
multQETGx( &(acadoWorkspace.QE[ 14 ]), &(acadoWorkspace.evGx[ 4 ]), &(acadoWorkspace.H10[ 4 ]) );
multQETGx( &(acadoWorkspace.QE[ 19 ]), &(acadoWorkspace.evGx[ 5 ]), &(acadoWorkspace.H10[ 4 ]) );
multQETGx( &(acadoWorkspace.QE[ 25 ]), &(acadoWorkspace.evGx[ 6 ]), &(acadoWorkspace.H10[ 4 ]) );
multQETGx( &(acadoWorkspace.QE[ 32 ]), &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.H10[ 4 ]) );
multQETGx( &(acadoWorkspace.QE[ 40 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.H10[ 4 ]) );
multQETGx( &(acadoWorkspace.QE[ 49 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 4 ]) );
zeroBlockH10( &(acadoWorkspace.H10[ 5 ]) );
multQETGx( &(acadoWorkspace.QE[ 20 ]), &(acadoWorkspace.evGx[ 5 ]), &(acadoWorkspace.H10[ 5 ]) );
multQETGx( &(acadoWorkspace.QE[ 26 ]), &(acadoWorkspace.evGx[ 6 ]), &(acadoWorkspace.H10[ 5 ]) );
multQETGx( &(acadoWorkspace.QE[ 33 ]), &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.H10[ 5 ]) );
multQETGx( &(acadoWorkspace.QE[ 41 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.H10[ 5 ]) );
multQETGx( &(acadoWorkspace.QE[ 50 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 5 ]) );
zeroBlockH10( &(acadoWorkspace.H10[ 6 ]) );
multQETGx( &(acadoWorkspace.QE[ 27 ]), &(acadoWorkspace.evGx[ 6 ]), &(acadoWorkspace.H10[ 6 ]) );
multQETGx( &(acadoWorkspace.QE[ 34 ]), &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.H10[ 6 ]) );
multQETGx( &(acadoWorkspace.QE[ 42 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.H10[ 6 ]) );
multQETGx( &(acadoWorkspace.QE[ 51 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 6 ]) );
zeroBlockH10( &(acadoWorkspace.H10[ 7 ]) );
multQETGx( &(acadoWorkspace.QE[ 35 ]), &(acadoWorkspace.evGx[ 7 ]), &(acadoWorkspace.H10[ 7 ]) );
multQETGx( &(acadoWorkspace.QE[ 43 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.H10[ 7 ]) );
multQETGx( &(acadoWorkspace.QE[ 52 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 7 ]) );
zeroBlockH10( &(acadoWorkspace.H10[ 8 ]) );
multQETGx( &(acadoWorkspace.QE[ 44 ]), &(acadoWorkspace.evGx[ 8 ]), &(acadoWorkspace.H10[ 8 ]) );
multQETGx( &(acadoWorkspace.QE[ 53 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 8 ]) );
zeroBlockH10( &(acadoWorkspace.H10[ 9 ]) );
multQETGx( &(acadoWorkspace.QE[ 54 ]), &(acadoWorkspace.evGx[ 9 ]), &(acadoWorkspace.H10[ 9 ]) );

setBlockH11_R1( 0, 0, acadoWorkspace.R1 );
setBlockH11( 0, 0, acadoWorkspace.E, acadoWorkspace.QE );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 1 ]), &(acadoWorkspace.QE[ 1 ]) );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 3 ]), &(acadoWorkspace.QE[ 3 ]) );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 6 ]), &(acadoWorkspace.QE[ 6 ]) );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 10 ]), &(acadoWorkspace.QE[ 10 ]) );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.QE[ 15 ]) );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QE[ 21 ]) );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 28 ]) );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 36 ]) );
setBlockH11( 0, 0, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 45 ]) );

zeroBlockH11( 0, 1 );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 1 ]), &(acadoWorkspace.QE[ 2 ]) );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 3 ]), &(acadoWorkspace.QE[ 4 ]) );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 6 ]), &(acadoWorkspace.QE[ 7 ]) );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 10 ]), &(acadoWorkspace.QE[ 11 ]) );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.QE[ 16 ]) );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QE[ 22 ]) );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 29 ]) );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 37 ]) );
setBlockH11( 0, 1, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 46 ]) );

zeroBlockH11( 0, 2 );
setBlockH11( 0, 2, &(acadoWorkspace.E[ 3 ]), &(acadoWorkspace.QE[ 5 ]) );
setBlockH11( 0, 2, &(acadoWorkspace.E[ 6 ]), &(acadoWorkspace.QE[ 8 ]) );
setBlockH11( 0, 2, &(acadoWorkspace.E[ 10 ]), &(acadoWorkspace.QE[ 12 ]) );
setBlockH11( 0, 2, &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.QE[ 17 ]) );
setBlockH11( 0, 2, &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QE[ 23 ]) );
setBlockH11( 0, 2, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 30 ]) );
setBlockH11( 0, 2, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 38 ]) );
setBlockH11( 0, 2, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 47 ]) );

zeroBlockH11( 0, 3 );
setBlockH11( 0, 3, &(acadoWorkspace.E[ 6 ]), &(acadoWorkspace.QE[ 9 ]) );
setBlockH11( 0, 3, &(acadoWorkspace.E[ 10 ]), &(acadoWorkspace.QE[ 13 ]) );
setBlockH11( 0, 3, &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.QE[ 18 ]) );
setBlockH11( 0, 3, &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QE[ 24 ]) );
setBlockH11( 0, 3, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 31 ]) );
setBlockH11( 0, 3, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 39 ]) );
setBlockH11( 0, 3, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 48 ]) );

zeroBlockH11( 0, 4 );
setBlockH11( 0, 4, &(acadoWorkspace.E[ 10 ]), &(acadoWorkspace.QE[ 14 ]) );
setBlockH11( 0, 4, &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.QE[ 19 ]) );
setBlockH11( 0, 4, &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QE[ 25 ]) );
setBlockH11( 0, 4, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 32 ]) );
setBlockH11( 0, 4, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 40 ]) );
setBlockH11( 0, 4, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 49 ]) );

zeroBlockH11( 0, 5 );
setBlockH11( 0, 5, &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.QE[ 20 ]) );
setBlockH11( 0, 5, &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QE[ 26 ]) );
setBlockH11( 0, 5, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 33 ]) );
setBlockH11( 0, 5, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 41 ]) );
setBlockH11( 0, 5, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 50 ]) );

zeroBlockH11( 0, 6 );
setBlockH11( 0, 6, &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QE[ 27 ]) );
setBlockH11( 0, 6, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 34 ]) );
setBlockH11( 0, 6, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 42 ]) );
setBlockH11( 0, 6, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 51 ]) );

zeroBlockH11( 0, 7 );
setBlockH11( 0, 7, &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QE[ 35 ]) );
setBlockH11( 0, 7, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 43 ]) );
setBlockH11( 0, 7, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 52 ]) );

zeroBlockH11( 0, 8 );
setBlockH11( 0, 8, &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 0, 8, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 0, 9 );
setBlockH11( 0, 9, &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 1, 1, &(acadoWorkspace.R1[ 1 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 2 ]), &(acadoWorkspace.QE[ 2 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 4 ]), &(acadoWorkspace.QE[ 4 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 7 ]), &(acadoWorkspace.QE[ 7 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 11 ]), &(acadoWorkspace.QE[ 11 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.QE[ 16 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.QE[ 22 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QE[ 29 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 37 ]) );
setBlockH11( 1, 1, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 46 ]) );

zeroBlockH11( 1, 2 );
setBlockH11( 1, 2, &(acadoWorkspace.E[ 4 ]), &(acadoWorkspace.QE[ 5 ]) );
setBlockH11( 1, 2, &(acadoWorkspace.E[ 7 ]), &(acadoWorkspace.QE[ 8 ]) );
setBlockH11( 1, 2, &(acadoWorkspace.E[ 11 ]), &(acadoWorkspace.QE[ 12 ]) );
setBlockH11( 1, 2, &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.QE[ 17 ]) );
setBlockH11( 1, 2, &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.QE[ 23 ]) );
setBlockH11( 1, 2, &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QE[ 30 ]) );
setBlockH11( 1, 2, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 38 ]) );
setBlockH11( 1, 2, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 47 ]) );

zeroBlockH11( 1, 3 );
setBlockH11( 1, 3, &(acadoWorkspace.E[ 7 ]), &(acadoWorkspace.QE[ 9 ]) );
setBlockH11( 1, 3, &(acadoWorkspace.E[ 11 ]), &(acadoWorkspace.QE[ 13 ]) );
setBlockH11( 1, 3, &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.QE[ 18 ]) );
setBlockH11( 1, 3, &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.QE[ 24 ]) );
setBlockH11( 1, 3, &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QE[ 31 ]) );
setBlockH11( 1, 3, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 39 ]) );
setBlockH11( 1, 3, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 48 ]) );

zeroBlockH11( 1, 4 );
setBlockH11( 1, 4, &(acadoWorkspace.E[ 11 ]), &(acadoWorkspace.QE[ 14 ]) );
setBlockH11( 1, 4, &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.QE[ 19 ]) );
setBlockH11( 1, 4, &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.QE[ 25 ]) );
setBlockH11( 1, 4, &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QE[ 32 ]) );
setBlockH11( 1, 4, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 40 ]) );
setBlockH11( 1, 4, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 49 ]) );

zeroBlockH11( 1, 5 );
setBlockH11( 1, 5, &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.QE[ 20 ]) );
setBlockH11( 1, 5, &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.QE[ 26 ]) );
setBlockH11( 1, 5, &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QE[ 33 ]) );
setBlockH11( 1, 5, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 41 ]) );
setBlockH11( 1, 5, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 50 ]) );

zeroBlockH11( 1, 6 );
setBlockH11( 1, 6, &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.QE[ 27 ]) );
setBlockH11( 1, 6, &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QE[ 34 ]) );
setBlockH11( 1, 6, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 42 ]) );
setBlockH11( 1, 6, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 51 ]) );

zeroBlockH11( 1, 7 );
setBlockH11( 1, 7, &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QE[ 35 ]) );
setBlockH11( 1, 7, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 43 ]) );
setBlockH11( 1, 7, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 52 ]) );

zeroBlockH11( 1, 8 );
setBlockH11( 1, 8, &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 1, 8, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 1, 9 );
setBlockH11( 1, 9, &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 2, 2, &(acadoWorkspace.R1[ 2 ]) );
setBlockH11( 2, 2, &(acadoWorkspace.E[ 5 ]), &(acadoWorkspace.QE[ 5 ]) );
setBlockH11( 2, 2, &(acadoWorkspace.E[ 8 ]), &(acadoWorkspace.QE[ 8 ]) );
setBlockH11( 2, 2, &(acadoWorkspace.E[ 12 ]), &(acadoWorkspace.QE[ 12 ]) );
setBlockH11( 2, 2, &(acadoWorkspace.E[ 17 ]), &(acadoWorkspace.QE[ 17 ]) );
setBlockH11( 2, 2, &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.QE[ 23 ]) );
setBlockH11( 2, 2, &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.QE[ 30 ]) );
setBlockH11( 2, 2, &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QE[ 38 ]) );
setBlockH11( 2, 2, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 47 ]) );

zeroBlockH11( 2, 3 );
setBlockH11( 2, 3, &(acadoWorkspace.E[ 8 ]), &(acadoWorkspace.QE[ 9 ]) );
setBlockH11( 2, 3, &(acadoWorkspace.E[ 12 ]), &(acadoWorkspace.QE[ 13 ]) );
setBlockH11( 2, 3, &(acadoWorkspace.E[ 17 ]), &(acadoWorkspace.QE[ 18 ]) );
setBlockH11( 2, 3, &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.QE[ 24 ]) );
setBlockH11( 2, 3, &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.QE[ 31 ]) );
setBlockH11( 2, 3, &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QE[ 39 ]) );
setBlockH11( 2, 3, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 48 ]) );

zeroBlockH11( 2, 4 );
setBlockH11( 2, 4, &(acadoWorkspace.E[ 12 ]), &(acadoWorkspace.QE[ 14 ]) );
setBlockH11( 2, 4, &(acadoWorkspace.E[ 17 ]), &(acadoWorkspace.QE[ 19 ]) );
setBlockH11( 2, 4, &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.QE[ 25 ]) );
setBlockH11( 2, 4, &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.QE[ 32 ]) );
setBlockH11( 2, 4, &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QE[ 40 ]) );
setBlockH11( 2, 4, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 49 ]) );

zeroBlockH11( 2, 5 );
setBlockH11( 2, 5, &(acadoWorkspace.E[ 17 ]), &(acadoWorkspace.QE[ 20 ]) );
setBlockH11( 2, 5, &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.QE[ 26 ]) );
setBlockH11( 2, 5, &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.QE[ 33 ]) );
setBlockH11( 2, 5, &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QE[ 41 ]) );
setBlockH11( 2, 5, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 50 ]) );

zeroBlockH11( 2, 6 );
setBlockH11( 2, 6, &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.QE[ 27 ]) );
setBlockH11( 2, 6, &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.QE[ 34 ]) );
setBlockH11( 2, 6, &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QE[ 42 ]) );
setBlockH11( 2, 6, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 51 ]) );

zeroBlockH11( 2, 7 );
setBlockH11( 2, 7, &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.QE[ 35 ]) );
setBlockH11( 2, 7, &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QE[ 43 ]) );
setBlockH11( 2, 7, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 52 ]) );

zeroBlockH11( 2, 8 );
setBlockH11( 2, 8, &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 2, 8, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 2, 9 );
setBlockH11( 2, 9, &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 3, 3, &(acadoWorkspace.R1[ 3 ]) );
setBlockH11( 3, 3, &(acadoWorkspace.E[ 9 ]), &(acadoWorkspace.QE[ 9 ]) );
setBlockH11( 3, 3, &(acadoWorkspace.E[ 13 ]), &(acadoWorkspace.QE[ 13 ]) );
setBlockH11( 3, 3, &(acadoWorkspace.E[ 18 ]), &(acadoWorkspace.QE[ 18 ]) );
setBlockH11( 3, 3, &(acadoWorkspace.E[ 24 ]), &(acadoWorkspace.QE[ 24 ]) );
setBlockH11( 3, 3, &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.QE[ 31 ]) );
setBlockH11( 3, 3, &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.QE[ 39 ]) );
setBlockH11( 3, 3, &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QE[ 48 ]) );

zeroBlockH11( 3, 4 );
setBlockH11( 3, 4, &(acadoWorkspace.E[ 13 ]), &(acadoWorkspace.QE[ 14 ]) );
setBlockH11( 3, 4, &(acadoWorkspace.E[ 18 ]), &(acadoWorkspace.QE[ 19 ]) );
setBlockH11( 3, 4, &(acadoWorkspace.E[ 24 ]), &(acadoWorkspace.QE[ 25 ]) );
setBlockH11( 3, 4, &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.QE[ 32 ]) );
setBlockH11( 3, 4, &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.QE[ 40 ]) );
setBlockH11( 3, 4, &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QE[ 49 ]) );

zeroBlockH11( 3, 5 );
setBlockH11( 3, 5, &(acadoWorkspace.E[ 18 ]), &(acadoWorkspace.QE[ 20 ]) );
setBlockH11( 3, 5, &(acadoWorkspace.E[ 24 ]), &(acadoWorkspace.QE[ 26 ]) );
setBlockH11( 3, 5, &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.QE[ 33 ]) );
setBlockH11( 3, 5, &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.QE[ 41 ]) );
setBlockH11( 3, 5, &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QE[ 50 ]) );

zeroBlockH11( 3, 6 );
setBlockH11( 3, 6, &(acadoWorkspace.E[ 24 ]), &(acadoWorkspace.QE[ 27 ]) );
setBlockH11( 3, 6, &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.QE[ 34 ]) );
setBlockH11( 3, 6, &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.QE[ 42 ]) );
setBlockH11( 3, 6, &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QE[ 51 ]) );

zeroBlockH11( 3, 7 );
setBlockH11( 3, 7, &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.QE[ 35 ]) );
setBlockH11( 3, 7, &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.QE[ 43 ]) );
setBlockH11( 3, 7, &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QE[ 52 ]) );

zeroBlockH11( 3, 8 );
setBlockH11( 3, 8, &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 3, 8, &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 3, 9 );
setBlockH11( 3, 9, &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 4, 4, &(acadoWorkspace.R1[ 4 ]) );
setBlockH11( 4, 4, &(acadoWorkspace.E[ 14 ]), &(acadoWorkspace.QE[ 14 ]) );
setBlockH11( 4, 4, &(acadoWorkspace.E[ 19 ]), &(acadoWorkspace.QE[ 19 ]) );
setBlockH11( 4, 4, &(acadoWorkspace.E[ 25 ]), &(acadoWorkspace.QE[ 25 ]) );
setBlockH11( 4, 4, &(acadoWorkspace.E[ 32 ]), &(acadoWorkspace.QE[ 32 ]) );
setBlockH11( 4, 4, &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.QE[ 40 ]) );
setBlockH11( 4, 4, &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.QE[ 49 ]) );

zeroBlockH11( 4, 5 );
setBlockH11( 4, 5, &(acadoWorkspace.E[ 19 ]), &(acadoWorkspace.QE[ 20 ]) );
setBlockH11( 4, 5, &(acadoWorkspace.E[ 25 ]), &(acadoWorkspace.QE[ 26 ]) );
setBlockH11( 4, 5, &(acadoWorkspace.E[ 32 ]), &(acadoWorkspace.QE[ 33 ]) );
setBlockH11( 4, 5, &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.QE[ 41 ]) );
setBlockH11( 4, 5, &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.QE[ 50 ]) );

zeroBlockH11( 4, 6 );
setBlockH11( 4, 6, &(acadoWorkspace.E[ 25 ]), &(acadoWorkspace.QE[ 27 ]) );
setBlockH11( 4, 6, &(acadoWorkspace.E[ 32 ]), &(acadoWorkspace.QE[ 34 ]) );
setBlockH11( 4, 6, &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.QE[ 42 ]) );
setBlockH11( 4, 6, &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.QE[ 51 ]) );

zeroBlockH11( 4, 7 );
setBlockH11( 4, 7, &(acadoWorkspace.E[ 32 ]), &(acadoWorkspace.QE[ 35 ]) );
setBlockH11( 4, 7, &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.QE[ 43 ]) );
setBlockH11( 4, 7, &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.QE[ 52 ]) );

zeroBlockH11( 4, 8 );
setBlockH11( 4, 8, &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 4, 8, &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 4, 9 );
setBlockH11( 4, 9, &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 5, 5, &(acadoWorkspace.R1[ 5 ]) );
setBlockH11( 5, 5, &(acadoWorkspace.E[ 20 ]), &(acadoWorkspace.QE[ 20 ]) );
setBlockH11( 5, 5, &(acadoWorkspace.E[ 26 ]), &(acadoWorkspace.QE[ 26 ]) );
setBlockH11( 5, 5, &(acadoWorkspace.E[ 33 ]), &(acadoWorkspace.QE[ 33 ]) );
setBlockH11( 5, 5, &(acadoWorkspace.E[ 41 ]), &(acadoWorkspace.QE[ 41 ]) );
setBlockH11( 5, 5, &(acadoWorkspace.E[ 50 ]), &(acadoWorkspace.QE[ 50 ]) );

zeroBlockH11( 5, 6 );
setBlockH11( 5, 6, &(acadoWorkspace.E[ 26 ]), &(acadoWorkspace.QE[ 27 ]) );
setBlockH11( 5, 6, &(acadoWorkspace.E[ 33 ]), &(acadoWorkspace.QE[ 34 ]) );
setBlockH11( 5, 6, &(acadoWorkspace.E[ 41 ]), &(acadoWorkspace.QE[ 42 ]) );
setBlockH11( 5, 6, &(acadoWorkspace.E[ 50 ]), &(acadoWorkspace.QE[ 51 ]) );

zeroBlockH11( 5, 7 );
setBlockH11( 5, 7, &(acadoWorkspace.E[ 33 ]), &(acadoWorkspace.QE[ 35 ]) );
setBlockH11( 5, 7, &(acadoWorkspace.E[ 41 ]), &(acadoWorkspace.QE[ 43 ]) );
setBlockH11( 5, 7, &(acadoWorkspace.E[ 50 ]), &(acadoWorkspace.QE[ 52 ]) );

zeroBlockH11( 5, 8 );
setBlockH11( 5, 8, &(acadoWorkspace.E[ 41 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 5, 8, &(acadoWorkspace.E[ 50 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 5, 9 );
setBlockH11( 5, 9, &(acadoWorkspace.E[ 50 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 6, 6, &(acadoWorkspace.R1[ 6 ]) );
setBlockH11( 6, 6, &(acadoWorkspace.E[ 27 ]), &(acadoWorkspace.QE[ 27 ]) );
setBlockH11( 6, 6, &(acadoWorkspace.E[ 34 ]), &(acadoWorkspace.QE[ 34 ]) );
setBlockH11( 6, 6, &(acadoWorkspace.E[ 42 ]), &(acadoWorkspace.QE[ 42 ]) );
setBlockH11( 6, 6, &(acadoWorkspace.E[ 51 ]), &(acadoWorkspace.QE[ 51 ]) );

zeroBlockH11( 6, 7 );
setBlockH11( 6, 7, &(acadoWorkspace.E[ 34 ]), &(acadoWorkspace.QE[ 35 ]) );
setBlockH11( 6, 7, &(acadoWorkspace.E[ 42 ]), &(acadoWorkspace.QE[ 43 ]) );
setBlockH11( 6, 7, &(acadoWorkspace.E[ 51 ]), &(acadoWorkspace.QE[ 52 ]) );

zeroBlockH11( 6, 8 );
setBlockH11( 6, 8, &(acadoWorkspace.E[ 42 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 6, 8, &(acadoWorkspace.E[ 51 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 6, 9 );
setBlockH11( 6, 9, &(acadoWorkspace.E[ 51 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 7, 7, &(acadoWorkspace.R1[ 7 ]) );
setBlockH11( 7, 7, &(acadoWorkspace.E[ 35 ]), &(acadoWorkspace.QE[ 35 ]) );
setBlockH11( 7, 7, &(acadoWorkspace.E[ 43 ]), &(acadoWorkspace.QE[ 43 ]) );
setBlockH11( 7, 7, &(acadoWorkspace.E[ 52 ]), &(acadoWorkspace.QE[ 52 ]) );

zeroBlockH11( 7, 8 );
setBlockH11( 7, 8, &(acadoWorkspace.E[ 43 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 7, 8, &(acadoWorkspace.E[ 52 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 7, 9 );
setBlockH11( 7, 9, &(acadoWorkspace.E[ 52 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 8, 8, &(acadoWorkspace.R1[ 8 ]) );
setBlockH11( 8, 8, &(acadoWorkspace.E[ 44 ]), &(acadoWorkspace.QE[ 44 ]) );
setBlockH11( 8, 8, &(acadoWorkspace.E[ 53 ]), &(acadoWorkspace.QE[ 53 ]) );

zeroBlockH11( 8, 9 );
setBlockH11( 8, 9, &(acadoWorkspace.E[ 53 ]), &(acadoWorkspace.QE[ 54 ]) );

setBlockH11_R1( 9, 9, &(acadoWorkspace.R1[ 9 ]) );
setBlockH11( 9, 9, &(acadoWorkspace.E[ 54 ]), &(acadoWorkspace.QE[ 54 ]) );


copyHTH( 1, 0 );
copyHTH( 2, 0 );
copyHTH( 2, 1 );
copyHTH( 3, 0 );
copyHTH( 3, 1 );
copyHTH( 3, 2 );
copyHTH( 4, 0 );
copyHTH( 4, 1 );
copyHTH( 4, 2 );
copyHTH( 4, 3 );
copyHTH( 5, 0 );
copyHTH( 5, 1 );
copyHTH( 5, 2 );
copyHTH( 5, 3 );
copyHTH( 5, 4 );
copyHTH( 6, 0 );
copyHTH( 6, 1 );
copyHTH( 6, 2 );
copyHTH( 6, 3 );
copyHTH( 6, 4 );
copyHTH( 6, 5 );
copyHTH( 7, 0 );
copyHTH( 7, 1 );
copyHTH( 7, 2 );
copyHTH( 7, 3 );
copyHTH( 7, 4 );
copyHTH( 7, 5 );
copyHTH( 7, 6 );
copyHTH( 8, 0 );
copyHTH( 8, 1 );
copyHTH( 8, 2 );
copyHTH( 8, 3 );
copyHTH( 8, 4 );
copyHTH( 8, 5 );
copyHTH( 8, 6 );
copyHTH( 8, 7 );
copyHTH( 9, 0 );
copyHTH( 9, 1 );
copyHTH( 9, 2 );
copyHTH( 9, 3 );
copyHTH( 9, 4 );
copyHTH( 9, 5 );
copyHTH( 9, 6 );
copyHTH( 9, 7 );
copyHTH( 9, 8 );

multQ1d( &(acadoWorkspace.Q1[ 1 ]), acadoWorkspace.d, acadoWorkspace.Qd );
multQ1d( &(acadoWorkspace.Q1[ 2 ]), &(acadoWorkspace.d[ 1 ]), &(acadoWorkspace.Qd[ 1 ]) );
multQ1d( &(acadoWorkspace.Q1[ 3 ]), &(acadoWorkspace.d[ 2 ]), &(acadoWorkspace.Qd[ 2 ]) );
multQ1d( &(acadoWorkspace.Q1[ 4 ]), &(acadoWorkspace.d[ 3 ]), &(acadoWorkspace.Qd[ 3 ]) );
multQ1d( &(acadoWorkspace.Q1[ 5 ]), &(acadoWorkspace.d[ 4 ]), &(acadoWorkspace.Qd[ 4 ]) );
multQ1d( &(acadoWorkspace.Q1[ 6 ]), &(acadoWorkspace.d[ 5 ]), &(acadoWorkspace.Qd[ 5 ]) );
multQ1d( &(acadoWorkspace.Q1[ 7 ]), &(acadoWorkspace.d[ 6 ]), &(acadoWorkspace.Qd[ 6 ]) );
multQ1d( &(acadoWorkspace.Q1[ 8 ]), &(acadoWorkspace.d[ 7 ]), &(acadoWorkspace.Qd[ 7 ]) );
multQ1d( &(acadoWorkspace.Q1[ 9 ]), &(acadoWorkspace.d[ 8 ]), &(acadoWorkspace.Qd[ 8 ]) );
multQN1d( acadoWorkspace.QN1, &(acadoWorkspace.d[ 9 ]), &(acadoWorkspace.Qd[ 9 ]) );

macETSlu( acadoWorkspace.QE, acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 1 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 3 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 6 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 10 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 15 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 21 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 28 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 36 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 45 ]), acadoWorkspace.g );
macETSlu( &(acadoWorkspace.QE[ 2 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 4 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 7 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 11 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 16 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 22 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 29 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 37 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 46 ]), &(acadoWorkspace.g[ 1 ]) );
macETSlu( &(acadoWorkspace.QE[ 5 ]), &(acadoWorkspace.g[ 2 ]) );
macETSlu( &(acadoWorkspace.QE[ 8 ]), &(acadoWorkspace.g[ 2 ]) );
macETSlu( &(acadoWorkspace.QE[ 12 ]), &(acadoWorkspace.g[ 2 ]) );
macETSlu( &(acadoWorkspace.QE[ 17 ]), &(acadoWorkspace.g[ 2 ]) );
macETSlu( &(acadoWorkspace.QE[ 23 ]), &(acadoWorkspace.g[ 2 ]) );
macETSlu( &(acadoWorkspace.QE[ 30 ]), &(acadoWorkspace.g[ 2 ]) );
macETSlu( &(acadoWorkspace.QE[ 38 ]), &(acadoWorkspace.g[ 2 ]) );
macETSlu( &(acadoWorkspace.QE[ 47 ]), &(acadoWorkspace.g[ 2 ]) );
macETSlu( &(acadoWorkspace.QE[ 9 ]), &(acadoWorkspace.g[ 3 ]) );
macETSlu( &(acadoWorkspace.QE[ 13 ]), &(acadoWorkspace.g[ 3 ]) );
macETSlu( &(acadoWorkspace.QE[ 18 ]), &(acadoWorkspace.g[ 3 ]) );
macETSlu( &(acadoWorkspace.QE[ 24 ]), &(acadoWorkspace.g[ 3 ]) );
macETSlu( &(acadoWorkspace.QE[ 31 ]), &(acadoWorkspace.g[ 3 ]) );
macETSlu( &(acadoWorkspace.QE[ 39 ]), &(acadoWorkspace.g[ 3 ]) );
macETSlu( &(acadoWorkspace.QE[ 48 ]), &(acadoWorkspace.g[ 3 ]) );
macETSlu( &(acadoWorkspace.QE[ 14 ]), &(acadoWorkspace.g[ 4 ]) );
macETSlu( &(acadoWorkspace.QE[ 19 ]), &(acadoWorkspace.g[ 4 ]) );
macETSlu( &(acadoWorkspace.QE[ 25 ]), &(acadoWorkspace.g[ 4 ]) );
macETSlu( &(acadoWorkspace.QE[ 32 ]), &(acadoWorkspace.g[ 4 ]) );
macETSlu( &(acadoWorkspace.QE[ 40 ]), &(acadoWorkspace.g[ 4 ]) );
macETSlu( &(acadoWorkspace.QE[ 49 ]), &(acadoWorkspace.g[ 4 ]) );
macETSlu( &(acadoWorkspace.QE[ 20 ]), &(acadoWorkspace.g[ 5 ]) );
macETSlu( &(acadoWorkspace.QE[ 26 ]), &(acadoWorkspace.g[ 5 ]) );
macETSlu( &(acadoWorkspace.QE[ 33 ]), &(acadoWorkspace.g[ 5 ]) );
macETSlu( &(acadoWorkspace.QE[ 41 ]), &(acadoWorkspace.g[ 5 ]) );
macETSlu( &(acadoWorkspace.QE[ 50 ]), &(acadoWorkspace.g[ 5 ]) );
macETSlu( &(acadoWorkspace.QE[ 27 ]), &(acadoWorkspace.g[ 6 ]) );
macETSlu( &(acadoWorkspace.QE[ 34 ]), &(acadoWorkspace.g[ 6 ]) );
macETSlu( &(acadoWorkspace.QE[ 42 ]), &(acadoWorkspace.g[ 6 ]) );
macETSlu( &(acadoWorkspace.QE[ 51 ]), &(acadoWorkspace.g[ 6 ]) );
macETSlu( &(acadoWorkspace.QE[ 35 ]), &(acadoWorkspace.g[ 7 ]) );
macETSlu( &(acadoWorkspace.QE[ 43 ]), &(acadoWorkspace.g[ 7 ]) );
macETSlu( &(acadoWorkspace.QE[ 52 ]), &(acadoWorkspace.g[ 7 ]) );
macETSlu( &(acadoWorkspace.QE[ 44 ]), &(acadoWorkspace.g[ 8 ]) );
macETSlu( &(acadoWorkspace.QE[ 53 ]), &(acadoWorkspace.g[ 8 ]) );
macETSlu( &(acadoWorkspace.QE[ 54 ]), &(acadoWorkspace.g[ 9 ]) );
acadoWorkspace.lb[0] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[0];
acadoWorkspace.lb[1] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[1];
acadoWorkspace.lb[2] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[2];
acadoWorkspace.lb[3] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[3];
acadoWorkspace.lb[4] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[4];
acadoWorkspace.lb[5] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[5];
acadoWorkspace.lb[6] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[6];
acadoWorkspace.lb[7] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[7];
acadoWorkspace.lb[8] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[8];
acadoWorkspace.lb[9] = (real_t)-3.0000000000000000e+00 - acadoVariables.u[9];
acadoWorkspace.ub[0] = (real_t)3.0000000000000000e+00 - acadoVariables.u[0];
acadoWorkspace.ub[1] = (real_t)3.0000000000000000e+00 - acadoVariables.u[1];
acadoWorkspace.ub[2] = (real_t)3.0000000000000000e+00 - acadoVariables.u[2];
acadoWorkspace.ub[3] = (real_t)3.0000000000000000e+00 - acadoVariables.u[3];
acadoWorkspace.ub[4] = (real_t)3.0000000000000000e+00 - acadoVariables.u[4];
acadoWorkspace.ub[5] = (real_t)3.0000000000000000e+00 - acadoVariables.u[5];
acadoWorkspace.ub[6] = (real_t)3.0000000000000000e+00 - acadoVariables.u[6];
acadoWorkspace.ub[7] = (real_t)3.0000000000000000e+00 - acadoVariables.u[7];
acadoWorkspace.ub[8] = (real_t)3.0000000000000000e+00 - acadoVariables.u[8];
acadoWorkspace.ub[9] = (real_t)3.0000000000000000e+00 - acadoVariables.u[9];

}

void condenseFdb(  )
{
acadoWorkspace.Dx0[0] = acadoVariables.x0[0] - acadoVariables.x[0];

acadoWorkspace.Dy[0] -= acadoVariables.y[0];
acadoWorkspace.Dy[1] -= acadoVariables.y[1];
acadoWorkspace.Dy[2] -= acadoVariables.y[2];
acadoWorkspace.Dy[3] -= acadoVariables.y[3];
acadoWorkspace.Dy[4] -= acadoVariables.y[4];
acadoWorkspace.Dy[5] -= acadoVariables.y[5];
acadoWorkspace.Dy[6] -= acadoVariables.y[6];
acadoWorkspace.Dy[7] -= acadoVariables.y[7];
acadoWorkspace.Dy[8] -= acadoVariables.y[8];
acadoWorkspace.Dy[9] -= acadoVariables.y[9];
acadoWorkspace.Dy[10] -= acadoVariables.y[10];
acadoWorkspace.Dy[11] -= acadoVariables.y[11];
acadoWorkspace.Dy[12] -= acadoVariables.y[12];
acadoWorkspace.Dy[13] -= acadoVariables.y[13];
acadoWorkspace.Dy[14] -= acadoVariables.y[14];
acadoWorkspace.Dy[15] -= acadoVariables.y[15];
acadoWorkspace.Dy[16] -= acadoVariables.y[16];
acadoWorkspace.Dy[17] -= acadoVariables.y[17];
acadoWorkspace.Dy[18] -= acadoVariables.y[18];
acadoWorkspace.Dy[19] -= acadoVariables.y[19];
acadoWorkspace.DyN[0] -= acadoVariables.yN[0];

multRDy( acadoWorkspace.R2, acadoWorkspace.Dy, acadoWorkspace.g );
multRDy( &(acadoWorkspace.R2[ 2 ]), &(acadoWorkspace.Dy[ 2 ]), &(acadoWorkspace.g[ 1 ]) );
multRDy( &(acadoWorkspace.R2[ 4 ]), &(acadoWorkspace.Dy[ 4 ]), &(acadoWorkspace.g[ 2 ]) );
multRDy( &(acadoWorkspace.R2[ 6 ]), &(acadoWorkspace.Dy[ 6 ]), &(acadoWorkspace.g[ 3 ]) );
multRDy( &(acadoWorkspace.R2[ 8 ]), &(acadoWorkspace.Dy[ 8 ]), &(acadoWorkspace.g[ 4 ]) );
multRDy( &(acadoWorkspace.R2[ 10 ]), &(acadoWorkspace.Dy[ 10 ]), &(acadoWorkspace.g[ 5 ]) );
multRDy( &(acadoWorkspace.R2[ 12 ]), &(acadoWorkspace.Dy[ 12 ]), &(acadoWorkspace.g[ 6 ]) );
multRDy( &(acadoWorkspace.R2[ 14 ]), &(acadoWorkspace.Dy[ 14 ]), &(acadoWorkspace.g[ 7 ]) );
multRDy( &(acadoWorkspace.R2[ 16 ]), &(acadoWorkspace.Dy[ 16 ]), &(acadoWorkspace.g[ 8 ]) );
multRDy( &(acadoWorkspace.R2[ 18 ]), &(acadoWorkspace.Dy[ 18 ]), &(acadoWorkspace.g[ 9 ]) );

multQDy( acadoWorkspace.Q2, acadoWorkspace.Dy, acadoWorkspace.QDy );
multQDy( &(acadoWorkspace.Q2[ 2 ]), &(acadoWorkspace.Dy[ 2 ]), &(acadoWorkspace.QDy[ 1 ]) );
multQDy( &(acadoWorkspace.Q2[ 4 ]), &(acadoWorkspace.Dy[ 4 ]), &(acadoWorkspace.QDy[ 2 ]) );
multQDy( &(acadoWorkspace.Q2[ 6 ]), &(acadoWorkspace.Dy[ 6 ]), &(acadoWorkspace.QDy[ 3 ]) );
multQDy( &(acadoWorkspace.Q2[ 8 ]), &(acadoWorkspace.Dy[ 8 ]), &(acadoWorkspace.QDy[ 4 ]) );
multQDy( &(acadoWorkspace.Q2[ 10 ]), &(acadoWorkspace.Dy[ 10 ]), &(acadoWorkspace.QDy[ 5 ]) );
multQDy( &(acadoWorkspace.Q2[ 12 ]), &(acadoWorkspace.Dy[ 12 ]), &(acadoWorkspace.QDy[ 6 ]) );
multQDy( &(acadoWorkspace.Q2[ 14 ]), &(acadoWorkspace.Dy[ 14 ]), &(acadoWorkspace.QDy[ 7 ]) );
multQDy( &(acadoWorkspace.Q2[ 16 ]), &(acadoWorkspace.Dy[ 16 ]), &(acadoWorkspace.QDy[ 8 ]) );
multQDy( &(acadoWorkspace.Q2[ 18 ]), &(acadoWorkspace.Dy[ 18 ]), &(acadoWorkspace.QDy[ 9 ]) );

acadoWorkspace.QDy[10] = + acadoWorkspace.QN2[0]*acadoWorkspace.DyN[0];

acadoWorkspace.QDy[1] += acadoWorkspace.Qd[0];
acadoWorkspace.QDy[2] += acadoWorkspace.Qd[1];
acadoWorkspace.QDy[3] += acadoWorkspace.Qd[2];
acadoWorkspace.QDy[4] += acadoWorkspace.Qd[3];
acadoWorkspace.QDy[5] += acadoWorkspace.Qd[4];
acadoWorkspace.QDy[6] += acadoWorkspace.Qd[5];
acadoWorkspace.QDy[7] += acadoWorkspace.Qd[6];
acadoWorkspace.QDy[8] += acadoWorkspace.Qd[7];
acadoWorkspace.QDy[9] += acadoWorkspace.Qd[8];
acadoWorkspace.QDy[10] += acadoWorkspace.Qd[9];

multEQDy( acadoWorkspace.E, &(acadoWorkspace.QDy[ 1 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 1 ]), &(acadoWorkspace.QDy[ 2 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 3 ]), &(acadoWorkspace.QDy[ 3 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 6 ]), &(acadoWorkspace.QDy[ 4 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 10 ]), &(acadoWorkspace.QDy[ 5 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 15 ]), &(acadoWorkspace.QDy[ 6 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 21 ]), &(acadoWorkspace.QDy[ 7 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 28 ]), &(acadoWorkspace.QDy[ 8 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 36 ]), &(acadoWorkspace.QDy[ 9 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 45 ]), &(acadoWorkspace.QDy[ 10 ]), acadoWorkspace.g );
multEQDy( &(acadoWorkspace.E[ 2 ]), &(acadoWorkspace.QDy[ 2 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 4 ]), &(acadoWorkspace.QDy[ 3 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 7 ]), &(acadoWorkspace.QDy[ 4 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 11 ]), &(acadoWorkspace.QDy[ 5 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.QDy[ 6 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.QDy[ 7 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.QDy[ 8 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.QDy[ 9 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 1 ]) );
multEQDy( &(acadoWorkspace.E[ 5 ]), &(acadoWorkspace.QDy[ 3 ]), &(acadoWorkspace.g[ 2 ]) );
multEQDy( &(acadoWorkspace.E[ 8 ]), &(acadoWorkspace.QDy[ 4 ]), &(acadoWorkspace.g[ 2 ]) );
multEQDy( &(acadoWorkspace.E[ 12 ]), &(acadoWorkspace.QDy[ 5 ]), &(acadoWorkspace.g[ 2 ]) );
multEQDy( &(acadoWorkspace.E[ 17 ]), &(acadoWorkspace.QDy[ 6 ]), &(acadoWorkspace.g[ 2 ]) );
multEQDy( &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.QDy[ 7 ]), &(acadoWorkspace.g[ 2 ]) );
multEQDy( &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.QDy[ 8 ]), &(acadoWorkspace.g[ 2 ]) );
multEQDy( &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.QDy[ 9 ]), &(acadoWorkspace.g[ 2 ]) );
multEQDy( &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 2 ]) );
multEQDy( &(acadoWorkspace.E[ 9 ]), &(acadoWorkspace.QDy[ 4 ]), &(acadoWorkspace.g[ 3 ]) );
multEQDy( &(acadoWorkspace.E[ 13 ]), &(acadoWorkspace.QDy[ 5 ]), &(acadoWorkspace.g[ 3 ]) );
multEQDy( &(acadoWorkspace.E[ 18 ]), &(acadoWorkspace.QDy[ 6 ]), &(acadoWorkspace.g[ 3 ]) );
multEQDy( &(acadoWorkspace.E[ 24 ]), &(acadoWorkspace.QDy[ 7 ]), &(acadoWorkspace.g[ 3 ]) );
multEQDy( &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.QDy[ 8 ]), &(acadoWorkspace.g[ 3 ]) );
multEQDy( &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.QDy[ 9 ]), &(acadoWorkspace.g[ 3 ]) );
multEQDy( &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 3 ]) );
multEQDy( &(acadoWorkspace.E[ 14 ]), &(acadoWorkspace.QDy[ 5 ]), &(acadoWorkspace.g[ 4 ]) );
multEQDy( &(acadoWorkspace.E[ 19 ]), &(acadoWorkspace.QDy[ 6 ]), &(acadoWorkspace.g[ 4 ]) );
multEQDy( &(acadoWorkspace.E[ 25 ]), &(acadoWorkspace.QDy[ 7 ]), &(acadoWorkspace.g[ 4 ]) );
multEQDy( &(acadoWorkspace.E[ 32 ]), &(acadoWorkspace.QDy[ 8 ]), &(acadoWorkspace.g[ 4 ]) );
multEQDy( &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.QDy[ 9 ]), &(acadoWorkspace.g[ 4 ]) );
multEQDy( &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 4 ]) );
multEQDy( &(acadoWorkspace.E[ 20 ]), &(acadoWorkspace.QDy[ 6 ]), &(acadoWorkspace.g[ 5 ]) );
multEQDy( &(acadoWorkspace.E[ 26 ]), &(acadoWorkspace.QDy[ 7 ]), &(acadoWorkspace.g[ 5 ]) );
multEQDy( &(acadoWorkspace.E[ 33 ]), &(acadoWorkspace.QDy[ 8 ]), &(acadoWorkspace.g[ 5 ]) );
multEQDy( &(acadoWorkspace.E[ 41 ]), &(acadoWorkspace.QDy[ 9 ]), &(acadoWorkspace.g[ 5 ]) );
multEQDy( &(acadoWorkspace.E[ 50 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 5 ]) );
multEQDy( &(acadoWorkspace.E[ 27 ]), &(acadoWorkspace.QDy[ 7 ]), &(acadoWorkspace.g[ 6 ]) );
multEQDy( &(acadoWorkspace.E[ 34 ]), &(acadoWorkspace.QDy[ 8 ]), &(acadoWorkspace.g[ 6 ]) );
multEQDy( &(acadoWorkspace.E[ 42 ]), &(acadoWorkspace.QDy[ 9 ]), &(acadoWorkspace.g[ 6 ]) );
multEQDy( &(acadoWorkspace.E[ 51 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 6 ]) );
multEQDy( &(acadoWorkspace.E[ 35 ]), &(acadoWorkspace.QDy[ 8 ]), &(acadoWorkspace.g[ 7 ]) );
multEQDy( &(acadoWorkspace.E[ 43 ]), &(acadoWorkspace.QDy[ 9 ]), &(acadoWorkspace.g[ 7 ]) );
multEQDy( &(acadoWorkspace.E[ 52 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 7 ]) );
multEQDy( &(acadoWorkspace.E[ 44 ]), &(acadoWorkspace.QDy[ 9 ]), &(acadoWorkspace.g[ 8 ]) );
multEQDy( &(acadoWorkspace.E[ 53 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 8 ]) );
multEQDy( &(acadoWorkspace.E[ 54 ]), &(acadoWorkspace.QDy[ 10 ]), &(acadoWorkspace.g[ 9 ]) );

acadoWorkspace.g[0] += + acadoWorkspace.H10[0]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[1] += + acadoWorkspace.H10[1]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[2] += + acadoWorkspace.H10[2]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[3] += + acadoWorkspace.H10[3]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[4] += + acadoWorkspace.H10[4]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[5] += + acadoWorkspace.H10[5]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[6] += + acadoWorkspace.H10[6]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[7] += + acadoWorkspace.H10[7]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[8] += + acadoWorkspace.H10[8]*acadoWorkspace.Dx0[0];
acadoWorkspace.g[9] += + acadoWorkspace.H10[9]*acadoWorkspace.Dx0[0];

}

void expand(  )
{
acadoVariables.u[0] += acadoWorkspace.x[0];
acadoVariables.u[1] += acadoWorkspace.x[1];
acadoVariables.u[2] += acadoWorkspace.x[2];
acadoVariables.u[3] += acadoWorkspace.x[3];
acadoVariables.u[4] += acadoWorkspace.x[4];
acadoVariables.u[5] += acadoWorkspace.x[5];
acadoVariables.u[6] += acadoWorkspace.x[6];
acadoVariables.u[7] += acadoWorkspace.x[7];
acadoVariables.u[8] += acadoWorkspace.x[8];
acadoVariables.u[9] += acadoWorkspace.x[9];

acadoVariables.x[0] += acadoWorkspace.Dx0[0];

acadoVariables.x[1] += + acadoWorkspace.evGx[0]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[0];
acadoVariables.x[2] += + acadoWorkspace.evGx[1]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[1];
acadoVariables.x[3] += + acadoWorkspace.evGx[2]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[2];
acadoVariables.x[4] += + acadoWorkspace.evGx[3]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[3];
acadoVariables.x[5] += + acadoWorkspace.evGx[4]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[4];
acadoVariables.x[6] += + acadoWorkspace.evGx[5]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[5];
acadoVariables.x[7] += + acadoWorkspace.evGx[6]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[6];
acadoVariables.x[8] += + acadoWorkspace.evGx[7]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[7];
acadoVariables.x[9] += + acadoWorkspace.evGx[8]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[8];
acadoVariables.x[10] += + acadoWorkspace.evGx[9]*acadoWorkspace.Dx0[0] + acadoWorkspace.d[9];

multEDu( acadoWorkspace.E, acadoWorkspace.x, &(acadoVariables.x[ 1 ]) );
multEDu( &(acadoWorkspace.E[ 1 ]), acadoWorkspace.x, &(acadoVariables.x[ 2 ]) );
multEDu( &(acadoWorkspace.E[ 2 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 2 ]) );
multEDu( &(acadoWorkspace.E[ 3 ]), acadoWorkspace.x, &(acadoVariables.x[ 3 ]) );
multEDu( &(acadoWorkspace.E[ 4 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 3 ]) );
multEDu( &(acadoWorkspace.E[ 5 ]), &(acadoWorkspace.x[ 2 ]), &(acadoVariables.x[ 3 ]) );
multEDu( &(acadoWorkspace.E[ 6 ]), acadoWorkspace.x, &(acadoVariables.x[ 4 ]) );
multEDu( &(acadoWorkspace.E[ 7 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 4 ]) );
multEDu( &(acadoWorkspace.E[ 8 ]), &(acadoWorkspace.x[ 2 ]), &(acadoVariables.x[ 4 ]) );
multEDu( &(acadoWorkspace.E[ 9 ]), &(acadoWorkspace.x[ 3 ]), &(acadoVariables.x[ 4 ]) );
multEDu( &(acadoWorkspace.E[ 10 ]), acadoWorkspace.x, &(acadoVariables.x[ 5 ]) );
multEDu( &(acadoWorkspace.E[ 11 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 5 ]) );
multEDu( &(acadoWorkspace.E[ 12 ]), &(acadoWorkspace.x[ 2 ]), &(acadoVariables.x[ 5 ]) );
multEDu( &(acadoWorkspace.E[ 13 ]), &(acadoWorkspace.x[ 3 ]), &(acadoVariables.x[ 5 ]) );
multEDu( &(acadoWorkspace.E[ 14 ]), &(acadoWorkspace.x[ 4 ]), &(acadoVariables.x[ 5 ]) );
multEDu( &(acadoWorkspace.E[ 15 ]), acadoWorkspace.x, &(acadoVariables.x[ 6 ]) );
multEDu( &(acadoWorkspace.E[ 16 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 6 ]) );
multEDu( &(acadoWorkspace.E[ 17 ]), &(acadoWorkspace.x[ 2 ]), &(acadoVariables.x[ 6 ]) );
multEDu( &(acadoWorkspace.E[ 18 ]), &(acadoWorkspace.x[ 3 ]), &(acadoVariables.x[ 6 ]) );
multEDu( &(acadoWorkspace.E[ 19 ]), &(acadoWorkspace.x[ 4 ]), &(acadoVariables.x[ 6 ]) );
multEDu( &(acadoWorkspace.E[ 20 ]), &(acadoWorkspace.x[ 5 ]), &(acadoVariables.x[ 6 ]) );
multEDu( &(acadoWorkspace.E[ 21 ]), acadoWorkspace.x, &(acadoVariables.x[ 7 ]) );
multEDu( &(acadoWorkspace.E[ 22 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 7 ]) );
multEDu( &(acadoWorkspace.E[ 23 ]), &(acadoWorkspace.x[ 2 ]), &(acadoVariables.x[ 7 ]) );
multEDu( &(acadoWorkspace.E[ 24 ]), &(acadoWorkspace.x[ 3 ]), &(acadoVariables.x[ 7 ]) );
multEDu( &(acadoWorkspace.E[ 25 ]), &(acadoWorkspace.x[ 4 ]), &(acadoVariables.x[ 7 ]) );
multEDu( &(acadoWorkspace.E[ 26 ]), &(acadoWorkspace.x[ 5 ]), &(acadoVariables.x[ 7 ]) );
multEDu( &(acadoWorkspace.E[ 27 ]), &(acadoWorkspace.x[ 6 ]), &(acadoVariables.x[ 7 ]) );
multEDu( &(acadoWorkspace.E[ 28 ]), acadoWorkspace.x, &(acadoVariables.x[ 8 ]) );
multEDu( &(acadoWorkspace.E[ 29 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 8 ]) );
multEDu( &(acadoWorkspace.E[ 30 ]), &(acadoWorkspace.x[ 2 ]), &(acadoVariables.x[ 8 ]) );
multEDu( &(acadoWorkspace.E[ 31 ]), &(acadoWorkspace.x[ 3 ]), &(acadoVariables.x[ 8 ]) );
multEDu( &(acadoWorkspace.E[ 32 ]), &(acadoWorkspace.x[ 4 ]), &(acadoVariables.x[ 8 ]) );
multEDu( &(acadoWorkspace.E[ 33 ]), &(acadoWorkspace.x[ 5 ]), &(acadoVariables.x[ 8 ]) );
multEDu( &(acadoWorkspace.E[ 34 ]), &(acadoWorkspace.x[ 6 ]), &(acadoVariables.x[ 8 ]) );
multEDu( &(acadoWorkspace.E[ 35 ]), &(acadoWorkspace.x[ 7 ]), &(acadoVariables.x[ 8 ]) );
multEDu( &(acadoWorkspace.E[ 36 ]), acadoWorkspace.x, &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 37 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 38 ]), &(acadoWorkspace.x[ 2 ]), &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 39 ]), &(acadoWorkspace.x[ 3 ]), &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 40 ]), &(acadoWorkspace.x[ 4 ]), &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 41 ]), &(acadoWorkspace.x[ 5 ]), &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 42 ]), &(acadoWorkspace.x[ 6 ]), &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 43 ]), &(acadoWorkspace.x[ 7 ]), &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 44 ]), &(acadoWorkspace.x[ 8 ]), &(acadoVariables.x[ 9 ]) );
multEDu( &(acadoWorkspace.E[ 45 ]), acadoWorkspace.x, &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 46 ]), &(acadoWorkspace.x[ 1 ]), &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 47 ]), &(acadoWorkspace.x[ 2 ]), &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 48 ]), &(acadoWorkspace.x[ 3 ]), &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 49 ]), &(acadoWorkspace.x[ 4 ]), &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 50 ]), &(acadoWorkspace.x[ 5 ]), &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 51 ]), &(acadoWorkspace.x[ 6 ]), &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 52 ]), &(acadoWorkspace.x[ 7 ]), &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 53 ]), &(acadoWorkspace.x[ 8 ]), &(acadoVariables.x[ 10 ]) );
multEDu( &(acadoWorkspace.E[ 54 ]), &(acadoWorkspace.x[ 9 ]), &(acadoVariables.x[ 10 ]) );
}

int preparationStep(  )
{
int ret;

ret = modelSimulation();
evaluateObjective(  );
condensePrep(  );
return ret;
}

int feedbackStep(  )
{
int tmp;

condenseFdb(  );

tmp = solve( );

expand(  );
return tmp;
}

int initializeSolver(  )
{
int ret;

/* This is a function which must be called once before any other function call! */


ret = 0;

memset(&acadoWorkspace, 0, sizeof( acadoWorkspace ));
return ret;
}

void initializeNodesByForwardSimulation(  )
{
int index;
for (index = 0; index < 10; ++index)
{
acadoWorkspace.state[0] = acadoVariables.x[index];
acadoWorkspace.state[3] = acadoVariables.u[index];

integrate(acadoWorkspace.state, index == 0);

acadoVariables.x[index + 1] = acadoWorkspace.state[0];
}
}

void shiftStates( int strategy, real_t* const xEnd, real_t* const uEnd )
{
int index;
for (index = 0; index < 10; ++index)
{
acadoVariables.x[index] = acadoVariables.x[index + 1];
}

if (strategy == 1 && xEnd != 0)
{
acadoVariables.x[10] = xEnd[0];
}
else if (strategy == 2) 
{
acadoWorkspace.state[0] = acadoVariables.x[10];
if (uEnd != 0)
{
acadoWorkspace.state[3] = uEnd[0];
}
else
{
acadoWorkspace.state[3] = acadoVariables.u[9];
}

integrate(acadoWorkspace.state, 1);

acadoVariables.x[10] = acadoWorkspace.state[0];
}
}

void shiftControls( real_t* const uEnd )
{
int index;
for (index = 0; index < 9; ++index)
{
acadoVariables.u[index] = acadoVariables.u[index + 1];
}

if (uEnd != 0)
{
acadoVariables.u[9] = uEnd[0];
}
}

real_t getKKT(  )
{
real_t kkt;

int index;
real_t prd;

kkt = + acadoWorkspace.g[0]*acadoWorkspace.x[0] + acadoWorkspace.g[1]*acadoWorkspace.x[1] + acadoWorkspace.g[2]*acadoWorkspace.x[2] + acadoWorkspace.g[3]*acadoWorkspace.x[3] + acadoWorkspace.g[4]*acadoWorkspace.x[4] + acadoWorkspace.g[5]*acadoWorkspace.x[5] + acadoWorkspace.g[6]*acadoWorkspace.x[6] + acadoWorkspace.g[7]*acadoWorkspace.x[7] + acadoWorkspace.g[8]*acadoWorkspace.x[8] + acadoWorkspace.g[9]*acadoWorkspace.x[9];
kkt = fabs( kkt );
for (index = 0; index < 10; ++index)
{
prd = acadoWorkspace.y[index];
if (prd > 1e-12)
kkt += fabs(acadoWorkspace.lb[index] * prd);
else if (prd < -1e-12)
kkt += fabs(acadoWorkspace.ub[index] * prd);
}
return kkt;
}

real_t getObjective(  )
{
real_t objVal;

int lRun1;
/** Row vector of size: 2 */
real_t tmpDy[ 2 ];

/** Column vector of size: 1 */
real_t tmpDyN[ 1 ];

for (lRun1 = 0; lRun1 < 10; ++lRun1)
{
acadoWorkspace.objValueIn[0] = acadoVariables.x[lRun1];
acadoWorkspace.objValueIn[1] = acadoVariables.u[lRun1];

evaluateLSQ( acadoWorkspace.objValueIn, acadoWorkspace.objValueOut );
acadoWorkspace.Dy[lRun1 * 2] = acadoWorkspace.objValueOut[0] - acadoVariables.y[lRun1 * 2];
acadoWorkspace.Dy[lRun1 * 2 + 1] = acadoWorkspace.objValueOut[1] - acadoVariables.y[lRun1 * 2 + 1];
}
acadoWorkspace.objValueIn[0] = acadoVariables.x[10];
evaluateLSQEndTerm( acadoWorkspace.objValueIn, acadoWorkspace.objValueOut );
acadoWorkspace.DyN[0] = acadoWorkspace.objValueOut[0] - acadoVariables.yN[0];
objVal = 0.0000000000000000e+00;
for (lRun1 = 0; lRun1 < 10; ++lRun1)
{
tmpDy[0] = + acadoWorkspace.Dy[lRun1 * 2]*acadoVariables.W[0];
tmpDy[1] = + acadoWorkspace.Dy[lRun1 * 2 + 1]*acadoVariables.W[3];
objVal += + acadoWorkspace.Dy[lRun1 * 2]*tmpDy[0] + acadoWorkspace.Dy[lRun1 * 2 + 1]*tmpDy[1];
}

tmpDyN[0] = + acadoWorkspace.DyN[0]*acadoVariables.WN[0];
objVal += + acadoWorkspace.DyN[0]*tmpDyN[0];

objVal *= 0.5;
return objVal;
}

