/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *    
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2014 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov, Rien Quirynen, KU Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC)
 *    under supervision of Moritz Diehl. All rights reserved.
 *    
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *    
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *    
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *    
 */


#include "acado_common.h"


void solve_dim2_triangular( real_t* const A, real_t* const b )
{

b[1] = b[1]/A[3];
b[0] -= + A[1]*b[1];
b[0] = b[0]/A[0];
}

real_t solve_dim2_system( real_t* const A, real_t* const b, int* const rk_perm )
{
real_t det;

int i;
int j;
int k;

int indexMax;

int intSwap;

real_t valueMax;

real_t temp;

for (i = 0; i < 2; ++i)
{
rk_perm[i] = i;
}
det = 1.0000000000000000e+00;
if(fabs(A[2]) > fabs(A[0])) {
acadoWorkspace.rk_dim2_swap = A[0];
A[0] = A[2];
A[2] = acadoWorkspace.rk_dim2_swap;
acadoWorkspace.rk_dim2_swap = A[1];
A[1] = A[3];
A[3] = acadoWorkspace.rk_dim2_swap;
acadoWorkspace.rk_dim2_swap = b[0];
b[0] = b[1];
b[1] = acadoWorkspace.rk_dim2_swap;
intSwap = rk_perm[0];
rk_perm[0] = rk_perm[1];
rk_perm[1] = intSwap;
}

A[2] = -A[2]/A[0];
A[3] += + A[2]*A[1];
b[1] += + A[2]*b[0];

det = + det*A[0];

det = + det*A[3];

det = fabs(det);
solve_dim2_triangular( A, b );
return det;
}

void solve_dim2_system_reuse( real_t* const A, real_t* const b, int* const rk_perm )
{

acadoWorkspace.rk_dim2_bPerm[0] = b[rk_perm[0]];
acadoWorkspace.rk_dim2_bPerm[1] = b[rk_perm[1]];
acadoWorkspace.rk_dim2_bPerm[1] += A[2]*acadoWorkspace.rk_dim2_bPerm[0];


solve_dim2_triangular( A, acadoWorkspace.rk_dim2_bPerm );
b[0] = acadoWorkspace.rk_dim2_bPerm[0];
b[1] = acadoWorkspace.rk_dim2_bPerm[1];
}



/** Matrix of size: 2 x 2 (row major format) */
static const real_t Ah_mat[ 4 ] = 
{ 2.5000000000000001e-02, 5.3867513459481292e-02, 
-3.8675134594812867e-03, 2.5000000000000001e-02 };


/* Fixed step size:0.1 */
int integrate( real_t* const rk_eta, int resetIntegrator )
{
int error;

int i;
int j;
int k;
int run;
int run1;
int tmp_index1;
int tmp_index2;

real_t det;

acadoWorkspace.rk_ttt = 0.0000000000000000e+00;
acadoWorkspace.rk_xxx[1] = rk_eta[3];

for (run = 0; run < 1; ++run)
{
if( resetIntegrator ) {
for (i = 0; i < 1; ++i)
{
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 1; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
rhs_jac( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_diffsTemp2[ run1 * 2 ]) );
for (j = 0; j < 1; ++j)
{
tmp_index1 = (run1) + (j);
acadoWorkspace.rk_A[tmp_index1 * 2] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 2) + (j * 2)];
if( 0 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 2) + (j)] -= 1.0000000000000000e+00;
acadoWorkspace.rk_A[tmp_index1 * 2 + 1] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 2) + (j * 2)];
if( 1 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 2) + (j + 1)] -= 1.0000000000000000e+00;
}
rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
acadoWorkspace.rk_b[run1] = acadoWorkspace.rk_kkk[run1] - acadoWorkspace.rk_rhsTemp[0];
}
det = solve_dim2_system( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim2_perm );
for (j = 0; j < 2; ++j)
{
acadoWorkspace.rk_kkk[j] += acadoWorkspace.rk_b[j];
}
}
}
for (i = 0; i < 5; ++i)
{
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 1; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
acadoWorkspace.rk_b[run1] = acadoWorkspace.rk_kkk[run1] - acadoWorkspace.rk_rhsTemp[0];
}
solve_dim2_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim2_perm );
for (j = 0; j < 2; ++j)
{
acadoWorkspace.rk_kkk[j] += acadoWorkspace.rk_b[j];
}
}
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 1; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
rhs_jac( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_diffsTemp2[ run1 * 2 ]) );
for (j = 0; j < 1; ++j)
{
tmp_index1 = (run1) + (j);
acadoWorkspace.rk_A[tmp_index1 * 2] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 2) + (j * 2)];
if( 0 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 2) + (j)] -= 1.0000000000000000e+00;
acadoWorkspace.rk_A[tmp_index1 * 2 + 1] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 2) + (j * 2)];
if( 1 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 2) + (j + 1)] -= 1.0000000000000000e+00;
}
}
for (run1 = 0; run1 < 1; ++run1)
{
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_b[i] = - acadoWorkspace.rk_diffsTemp2[(i * 2) + (run1)];
}
if( 0 == run1 ) {
det = solve_dim2_system( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim2_perm );
}
 else {
solve_dim2_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim2_perm );
}
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffK[i] = acadoWorkspace.rk_b[i];
}
for (i = 0; i < 1; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 2) + (run1)] = (i == run1-0);
acadoWorkspace.rk_diffsNew2[(i * 2) + (run1)] += + acadoWorkspace.rk_diffK[i * 2]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_diffK[i * 2 + 1]*(real_t)5.0000000000000003e-02;
}
}
for (run1 = 0; run1 < 1; ++run1)
{
for (i = 0; i < 2; ++i)
{
for (j = 0; j < 1; ++j)
{
tmp_index1 = (i) + (j);
tmp_index2 = (run1) + (j * 2);
acadoWorkspace.rk_b[tmp_index1] = - acadoWorkspace.rk_diffsTemp2[(i * 2) + (tmp_index2 + 1)];
}
}
solve_dim2_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim2_perm );
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffK[i] = acadoWorkspace.rk_b[i];
}
for (i = 0; i < 1; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 2) + (run1 + 1)] = + acadoWorkspace.rk_diffK[i * 2]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_diffK[i * 2 + 1]*(real_t)5.0000000000000003e-02;
}
}
rk_eta[0] += + acadoWorkspace.rk_kkk[0]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[1]*(real_t)5.0000000000000003e-02;
for (i = 0; i < 1; ++i)
{
for (j = 0; j < 1; ++j)
{
tmp_index2 = (j) + (i);
rk_eta[tmp_index2 + 1] = acadoWorkspace.rk_diffsNew2[(i * 2) + (j)];
}
for (j = 0; j < 1; ++j)
{
tmp_index2 = (j) + (i);
rk_eta[tmp_index2 + 2] = acadoWorkspace.rk_diffsNew2[(i * 2) + (j + 1)];
}
}
resetIntegrator = 0;
acadoWorkspace.rk_ttt += 1.0000000000000000e+00;
}
for (i = 0; i < 1; ++i)
{
}
if( det < 1e-12 ) {
error = 2;
} else if( det < 1e-6 ) {
error = 1;
} else {
error = 0;
}
return error;
}



