/*
 *    This file was auto-generated by ACADO Code Generation Tool.
 *    
 *    ACADO Code Generation tool is a sub-package of ACADO toolkit --
 *    A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2014 by Boris Houska, Hans Joachim Ferreau,
 *    Milan Vukov, Rien Quirynen, KU Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC)
 *    under supervision of Moritz Diehl. All rights reserved.
 *    
 *    ACADO Toolkit is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 3 of the License, or (at your option) any later version.
 *    
 *    ACADO Toolkit is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 *    
 *    You should have received a copy of the GNU Lesser General Public
 *    License along with ACADO Toolkit; if not, write to the Free Software
 *    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *    
 */


#include "acado_common.h"


void solve_dim24_triangular( real_t* const A, real_t* const b )
{

b[23] = b[23]/A[575];
b[22] -= + A[551]*b[23];
b[22] = b[22]/A[550];
b[21] -= + A[527]*b[23];
b[21] -= + A[526]*b[22];
b[21] = b[21]/A[525];
b[20] -= + A[503]*b[23];
b[20] -= + A[502]*b[22];
b[20] -= + A[501]*b[21];
b[20] = b[20]/A[500];
b[19] -= + A[479]*b[23];
b[19] -= + A[478]*b[22];
b[19] -= + A[477]*b[21];
b[19] -= + A[476]*b[20];
b[19] = b[19]/A[475];
b[18] -= + A[455]*b[23];
b[18] -= + A[454]*b[22];
b[18] -= + A[453]*b[21];
b[18] -= + A[452]*b[20];
b[18] -= + A[451]*b[19];
b[18] = b[18]/A[450];
b[17] -= + A[431]*b[23];
b[17] -= + A[430]*b[22];
b[17] -= + A[429]*b[21];
b[17] -= + A[428]*b[20];
b[17] -= + A[427]*b[19];
b[17] -= + A[426]*b[18];
b[17] = b[17]/A[425];
b[16] -= + A[407]*b[23];
b[16] -= + A[406]*b[22];
b[16] -= + A[405]*b[21];
b[16] -= + A[404]*b[20];
b[16] -= + A[403]*b[19];
b[16] -= + A[402]*b[18];
b[16] -= + A[401]*b[17];
b[16] = b[16]/A[400];
b[15] -= + A[383]*b[23];
b[15] -= + A[382]*b[22];
b[15] -= + A[381]*b[21];
b[15] -= + A[380]*b[20];
b[15] -= + A[379]*b[19];
b[15] -= + A[378]*b[18];
b[15] -= + A[377]*b[17];
b[15] -= + A[376]*b[16];
b[15] = b[15]/A[375];
b[14] -= + A[359]*b[23];
b[14] -= + A[358]*b[22];
b[14] -= + A[357]*b[21];
b[14] -= + A[356]*b[20];
b[14] -= + A[355]*b[19];
b[14] -= + A[354]*b[18];
b[14] -= + A[353]*b[17];
b[14] -= + A[352]*b[16];
b[14] -= + A[351]*b[15];
b[14] = b[14]/A[350];
b[13] -= + A[335]*b[23];
b[13] -= + A[334]*b[22];
b[13] -= + A[333]*b[21];
b[13] -= + A[332]*b[20];
b[13] -= + A[331]*b[19];
b[13] -= + A[330]*b[18];
b[13] -= + A[329]*b[17];
b[13] -= + A[328]*b[16];
b[13] -= + A[327]*b[15];
b[13] -= + A[326]*b[14];
b[13] = b[13]/A[325];
b[12] -= + A[311]*b[23];
b[12] -= + A[310]*b[22];
b[12] -= + A[309]*b[21];
b[12] -= + A[308]*b[20];
b[12] -= + A[307]*b[19];
b[12] -= + A[306]*b[18];
b[12] -= + A[305]*b[17];
b[12] -= + A[304]*b[16];
b[12] -= + A[303]*b[15];
b[12] -= + A[302]*b[14];
b[12] -= + A[301]*b[13];
b[12] = b[12]/A[300];
b[11] -= + A[287]*b[23];
b[11] -= + A[286]*b[22];
b[11] -= + A[285]*b[21];
b[11] -= + A[284]*b[20];
b[11] -= + A[283]*b[19];
b[11] -= + A[282]*b[18];
b[11] -= + A[281]*b[17];
b[11] -= + A[280]*b[16];
b[11] -= + A[279]*b[15];
b[11] -= + A[278]*b[14];
b[11] -= + A[277]*b[13];
b[11] -= + A[276]*b[12];
b[11] = b[11]/A[275];
b[10] -= + A[263]*b[23];
b[10] -= + A[262]*b[22];
b[10] -= + A[261]*b[21];
b[10] -= + A[260]*b[20];
b[10] -= + A[259]*b[19];
b[10] -= + A[258]*b[18];
b[10] -= + A[257]*b[17];
b[10] -= + A[256]*b[16];
b[10] -= + A[255]*b[15];
b[10] -= + A[254]*b[14];
b[10] -= + A[253]*b[13];
b[10] -= + A[252]*b[12];
b[10] -= + A[251]*b[11];
b[10] = b[10]/A[250];
b[9] -= + A[239]*b[23];
b[9] -= + A[238]*b[22];
b[9] -= + A[237]*b[21];
b[9] -= + A[236]*b[20];
b[9] -= + A[235]*b[19];
b[9] -= + A[234]*b[18];
b[9] -= + A[233]*b[17];
b[9] -= + A[232]*b[16];
b[9] -= + A[231]*b[15];
b[9] -= + A[230]*b[14];
b[9] -= + A[229]*b[13];
b[9] -= + A[228]*b[12];
b[9] -= + A[227]*b[11];
b[9] -= + A[226]*b[10];
b[9] = b[9]/A[225];
b[8] -= + A[215]*b[23];
b[8] -= + A[214]*b[22];
b[8] -= + A[213]*b[21];
b[8] -= + A[212]*b[20];
b[8] -= + A[211]*b[19];
b[8] -= + A[210]*b[18];
b[8] -= + A[209]*b[17];
b[8] -= + A[208]*b[16];
b[8] -= + A[207]*b[15];
b[8] -= + A[206]*b[14];
b[8] -= + A[205]*b[13];
b[8] -= + A[204]*b[12];
b[8] -= + A[203]*b[11];
b[8] -= + A[202]*b[10];
b[8] -= + A[201]*b[9];
b[8] = b[8]/A[200];
b[7] -= + A[191]*b[23];
b[7] -= + A[190]*b[22];
b[7] -= + A[189]*b[21];
b[7] -= + A[188]*b[20];
b[7] -= + A[187]*b[19];
b[7] -= + A[186]*b[18];
b[7] -= + A[185]*b[17];
b[7] -= + A[184]*b[16];
b[7] -= + A[183]*b[15];
b[7] -= + A[182]*b[14];
b[7] -= + A[181]*b[13];
b[7] -= + A[180]*b[12];
b[7] -= + A[179]*b[11];
b[7] -= + A[178]*b[10];
b[7] -= + A[177]*b[9];
b[7] -= + A[176]*b[8];
b[7] = b[7]/A[175];
b[6] -= + A[167]*b[23];
b[6] -= + A[166]*b[22];
b[6] -= + A[165]*b[21];
b[6] -= + A[164]*b[20];
b[6] -= + A[163]*b[19];
b[6] -= + A[162]*b[18];
b[6] -= + A[161]*b[17];
b[6] -= + A[160]*b[16];
b[6] -= + A[159]*b[15];
b[6] -= + A[158]*b[14];
b[6] -= + A[157]*b[13];
b[6] -= + A[156]*b[12];
b[6] -= + A[155]*b[11];
b[6] -= + A[154]*b[10];
b[6] -= + A[153]*b[9];
b[6] -= + A[152]*b[8];
b[6] -= + A[151]*b[7];
b[6] = b[6]/A[150];
b[5] -= + A[143]*b[23];
b[5] -= + A[142]*b[22];
b[5] -= + A[141]*b[21];
b[5] -= + A[140]*b[20];
b[5] -= + A[139]*b[19];
b[5] -= + A[138]*b[18];
b[5] -= + A[137]*b[17];
b[5] -= + A[136]*b[16];
b[5] -= + A[135]*b[15];
b[5] -= + A[134]*b[14];
b[5] -= + A[133]*b[13];
b[5] -= + A[132]*b[12];
b[5] -= + A[131]*b[11];
b[5] -= + A[130]*b[10];
b[5] -= + A[129]*b[9];
b[5] -= + A[128]*b[8];
b[5] -= + A[127]*b[7];
b[5] -= + A[126]*b[6];
b[5] = b[5]/A[125];
b[4] -= + A[119]*b[23];
b[4] -= + A[118]*b[22];
b[4] -= + A[117]*b[21];
b[4] -= + A[116]*b[20];
b[4] -= + A[115]*b[19];
b[4] -= + A[114]*b[18];
b[4] -= + A[113]*b[17];
b[4] -= + A[112]*b[16];
b[4] -= + A[111]*b[15];
b[4] -= + A[110]*b[14];
b[4] -= + A[109]*b[13];
b[4] -= + A[108]*b[12];
b[4] -= + A[107]*b[11];
b[4] -= + A[106]*b[10];
b[4] -= + A[105]*b[9];
b[4] -= + A[104]*b[8];
b[4] -= + A[103]*b[7];
b[4] -= + A[102]*b[6];
b[4] -= + A[101]*b[5];
b[4] = b[4]/A[100];
b[3] -= + A[95]*b[23];
b[3] -= + A[94]*b[22];
b[3] -= + A[93]*b[21];
b[3] -= + A[92]*b[20];
b[3] -= + A[91]*b[19];
b[3] -= + A[90]*b[18];
b[3] -= + A[89]*b[17];
b[3] -= + A[88]*b[16];
b[3] -= + A[87]*b[15];
b[3] -= + A[86]*b[14];
b[3] -= + A[85]*b[13];
b[3] -= + A[84]*b[12];
b[3] -= + A[83]*b[11];
b[3] -= + A[82]*b[10];
b[3] -= + A[81]*b[9];
b[3] -= + A[80]*b[8];
b[3] -= + A[79]*b[7];
b[3] -= + A[78]*b[6];
b[3] -= + A[77]*b[5];
b[3] -= + A[76]*b[4];
b[3] = b[3]/A[75];
b[2] -= + A[71]*b[23];
b[2] -= + A[70]*b[22];
b[2] -= + A[69]*b[21];
b[2] -= + A[68]*b[20];
b[2] -= + A[67]*b[19];
b[2] -= + A[66]*b[18];
b[2] -= + A[65]*b[17];
b[2] -= + A[64]*b[16];
b[2] -= + A[63]*b[15];
b[2] -= + A[62]*b[14];
b[2] -= + A[61]*b[13];
b[2] -= + A[60]*b[12];
b[2] -= + A[59]*b[11];
b[2] -= + A[58]*b[10];
b[2] -= + A[57]*b[9];
b[2] -= + A[56]*b[8];
b[2] -= + A[55]*b[7];
b[2] -= + A[54]*b[6];
b[2] -= + A[53]*b[5];
b[2] -= + A[52]*b[4];
b[2] -= + A[51]*b[3];
b[2] = b[2]/A[50];
b[1] -= + A[47]*b[23];
b[1] -= + A[46]*b[22];
b[1] -= + A[45]*b[21];
b[1] -= + A[44]*b[20];
b[1] -= + A[43]*b[19];
b[1] -= + A[42]*b[18];
b[1] -= + A[41]*b[17];
b[1] -= + A[40]*b[16];
b[1] -= + A[39]*b[15];
b[1] -= + A[38]*b[14];
b[1] -= + A[37]*b[13];
b[1] -= + A[36]*b[12];
b[1] -= + A[35]*b[11];
b[1] -= + A[34]*b[10];
b[1] -= + A[33]*b[9];
b[1] -= + A[32]*b[8];
b[1] -= + A[31]*b[7];
b[1] -= + A[30]*b[6];
b[1] -= + A[29]*b[5];
b[1] -= + A[28]*b[4];
b[1] -= + A[27]*b[3];
b[1] -= + A[26]*b[2];
b[1] = b[1]/A[25];
b[0] -= + A[23]*b[23];
b[0] -= + A[22]*b[22];
b[0] -= + A[21]*b[21];
b[0] -= + A[20]*b[20];
b[0] -= + A[19]*b[19];
b[0] -= + A[18]*b[18];
b[0] -= + A[17]*b[17];
b[0] -= + A[16]*b[16];
b[0] -= + A[15]*b[15];
b[0] -= + A[14]*b[14];
b[0] -= + A[13]*b[13];
b[0] -= + A[12]*b[12];
b[0] -= + A[11]*b[11];
b[0] -= + A[10]*b[10];
b[0] -= + A[9]*b[9];
b[0] -= + A[8]*b[8];
b[0] -= + A[7]*b[7];
b[0] -= + A[6]*b[6];
b[0] -= + A[5]*b[5];
b[0] -= + A[4]*b[4];
b[0] -= + A[3]*b[3];
b[0] -= + A[2]*b[2];
b[0] -= + A[1]*b[1];
b[0] = b[0]/A[0];
}

real_t solve_dim24_system( real_t* const A, real_t* const b, int* const rk_perm )
{
real_t det;

int i;
int j;
int k;

int indexMax;

int intSwap;

real_t valueMax;

real_t temp;

for (i = 0; i < 24; ++i)
{
rk_perm[i] = i;
}
det = 1.0000000000000000e+00;
for( i=0; i < (23); i++ ) {
	indexMax = i;
	valueMax = fabs(A[i*24+i]);
	for( j=(i+1); j < 24; j++ ) {
		temp = fabs(A[j*24+i]);
		if( temp > valueMax ) {
			indexMax = j;
			valueMax = temp;
		}
	}
	if( indexMax > i ) {
for (k = 0; k < 24; ++k)
{
	acadoWorkspace.rk_dim24_swap = A[i*24+k];
	A[i*24+k] = A[indexMax*24+k];
	A[indexMax*24+k] = acadoWorkspace.rk_dim24_swap;
}
	acadoWorkspace.rk_dim24_swap = b[i];
	b[i] = b[indexMax];
	b[indexMax] = acadoWorkspace.rk_dim24_swap;
	intSwap = rk_perm[i];
	rk_perm[i] = rk_perm[indexMax];
	rk_perm[indexMax] = intSwap;
	}
	det *= A[i*24+i];
	for( j=i+1; j < 24; j++ ) {
		A[j*24+i] = -A[j*24+i]/A[i*24+i];
		for( k=i+1; k < 24; k++ ) {
			A[j*24+k] += A[j*24+i] * A[i*24+k];
		}
		b[j] += A[j*24+i] * b[i];
	}
}
det *= A[575];
det = fabs(det);
solve_dim24_triangular( A, b );
return det;
}

void solve_dim24_system_reuse( real_t* const A, real_t* const b, int* const rk_perm )
{

acadoWorkspace.rk_dim24_bPerm[0] = b[rk_perm[0]];
acadoWorkspace.rk_dim24_bPerm[1] = b[rk_perm[1]];
acadoWorkspace.rk_dim24_bPerm[2] = b[rk_perm[2]];
acadoWorkspace.rk_dim24_bPerm[3] = b[rk_perm[3]];
acadoWorkspace.rk_dim24_bPerm[4] = b[rk_perm[4]];
acadoWorkspace.rk_dim24_bPerm[5] = b[rk_perm[5]];
acadoWorkspace.rk_dim24_bPerm[6] = b[rk_perm[6]];
acadoWorkspace.rk_dim24_bPerm[7] = b[rk_perm[7]];
acadoWorkspace.rk_dim24_bPerm[8] = b[rk_perm[8]];
acadoWorkspace.rk_dim24_bPerm[9] = b[rk_perm[9]];
acadoWorkspace.rk_dim24_bPerm[10] = b[rk_perm[10]];
acadoWorkspace.rk_dim24_bPerm[11] = b[rk_perm[11]];
acadoWorkspace.rk_dim24_bPerm[12] = b[rk_perm[12]];
acadoWorkspace.rk_dim24_bPerm[13] = b[rk_perm[13]];
acadoWorkspace.rk_dim24_bPerm[14] = b[rk_perm[14]];
acadoWorkspace.rk_dim24_bPerm[15] = b[rk_perm[15]];
acadoWorkspace.rk_dim24_bPerm[16] = b[rk_perm[16]];
acadoWorkspace.rk_dim24_bPerm[17] = b[rk_perm[17]];
acadoWorkspace.rk_dim24_bPerm[18] = b[rk_perm[18]];
acadoWorkspace.rk_dim24_bPerm[19] = b[rk_perm[19]];
acadoWorkspace.rk_dim24_bPerm[20] = b[rk_perm[20]];
acadoWorkspace.rk_dim24_bPerm[21] = b[rk_perm[21]];
acadoWorkspace.rk_dim24_bPerm[22] = b[rk_perm[22]];
acadoWorkspace.rk_dim24_bPerm[23] = b[rk_perm[23]];
acadoWorkspace.rk_dim24_bPerm[1] += A[24]*acadoWorkspace.rk_dim24_bPerm[0];

acadoWorkspace.rk_dim24_bPerm[2] += A[48]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[2] += A[49]*acadoWorkspace.rk_dim24_bPerm[1];

acadoWorkspace.rk_dim24_bPerm[3] += A[72]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[3] += A[73]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[3] += A[74]*acadoWorkspace.rk_dim24_bPerm[2];

acadoWorkspace.rk_dim24_bPerm[4] += A[96]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[4] += A[97]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[4] += A[98]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[4] += A[99]*acadoWorkspace.rk_dim24_bPerm[3];

acadoWorkspace.rk_dim24_bPerm[5] += A[120]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[5] += A[121]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[5] += A[122]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[5] += A[123]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[5] += A[124]*acadoWorkspace.rk_dim24_bPerm[4];

acadoWorkspace.rk_dim24_bPerm[6] += A[144]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[6] += A[145]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[6] += A[146]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[6] += A[147]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[6] += A[148]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[6] += A[149]*acadoWorkspace.rk_dim24_bPerm[5];

acadoWorkspace.rk_dim24_bPerm[7] += A[168]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[7] += A[169]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[7] += A[170]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[7] += A[171]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[7] += A[172]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[7] += A[173]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[7] += A[174]*acadoWorkspace.rk_dim24_bPerm[6];

acadoWorkspace.rk_dim24_bPerm[8] += A[192]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[8] += A[193]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[8] += A[194]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[8] += A[195]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[8] += A[196]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[8] += A[197]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[8] += A[198]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[8] += A[199]*acadoWorkspace.rk_dim24_bPerm[7];

acadoWorkspace.rk_dim24_bPerm[9] += A[216]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[9] += A[217]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[9] += A[218]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[9] += A[219]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[9] += A[220]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[9] += A[221]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[9] += A[222]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[9] += A[223]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[9] += A[224]*acadoWorkspace.rk_dim24_bPerm[8];

acadoWorkspace.rk_dim24_bPerm[10] += A[240]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[10] += A[241]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[10] += A[242]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[10] += A[243]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[10] += A[244]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[10] += A[245]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[10] += A[246]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[10] += A[247]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[10] += A[248]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[10] += A[249]*acadoWorkspace.rk_dim24_bPerm[9];

acadoWorkspace.rk_dim24_bPerm[11] += A[264]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[11] += A[265]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[11] += A[266]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[11] += A[267]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[11] += A[268]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[11] += A[269]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[11] += A[270]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[11] += A[271]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[11] += A[272]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[11] += A[273]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[11] += A[274]*acadoWorkspace.rk_dim24_bPerm[10];

acadoWorkspace.rk_dim24_bPerm[12] += A[288]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[12] += A[289]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[12] += A[290]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[12] += A[291]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[12] += A[292]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[12] += A[293]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[12] += A[294]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[12] += A[295]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[12] += A[296]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[12] += A[297]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[12] += A[298]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[12] += A[299]*acadoWorkspace.rk_dim24_bPerm[11];

acadoWorkspace.rk_dim24_bPerm[13] += A[312]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[13] += A[313]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[13] += A[314]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[13] += A[315]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[13] += A[316]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[13] += A[317]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[13] += A[318]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[13] += A[319]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[13] += A[320]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[13] += A[321]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[13] += A[322]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[13] += A[323]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[13] += A[324]*acadoWorkspace.rk_dim24_bPerm[12];

acadoWorkspace.rk_dim24_bPerm[14] += A[336]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[14] += A[337]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[14] += A[338]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[14] += A[339]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[14] += A[340]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[14] += A[341]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[14] += A[342]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[14] += A[343]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[14] += A[344]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[14] += A[345]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[14] += A[346]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[14] += A[347]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[14] += A[348]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[14] += A[349]*acadoWorkspace.rk_dim24_bPerm[13];

acadoWorkspace.rk_dim24_bPerm[15] += A[360]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[15] += A[361]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[15] += A[362]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[15] += A[363]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[15] += A[364]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[15] += A[365]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[15] += A[366]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[15] += A[367]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[15] += A[368]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[15] += A[369]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[15] += A[370]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[15] += A[371]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[15] += A[372]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[15] += A[373]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[15] += A[374]*acadoWorkspace.rk_dim24_bPerm[14];

acadoWorkspace.rk_dim24_bPerm[16] += A[384]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[16] += A[385]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[16] += A[386]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[16] += A[387]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[16] += A[388]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[16] += A[389]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[16] += A[390]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[16] += A[391]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[16] += A[392]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[16] += A[393]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[16] += A[394]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[16] += A[395]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[16] += A[396]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[16] += A[397]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[16] += A[398]*acadoWorkspace.rk_dim24_bPerm[14];
acadoWorkspace.rk_dim24_bPerm[16] += A[399]*acadoWorkspace.rk_dim24_bPerm[15];

acadoWorkspace.rk_dim24_bPerm[17] += A[408]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[17] += A[409]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[17] += A[410]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[17] += A[411]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[17] += A[412]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[17] += A[413]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[17] += A[414]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[17] += A[415]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[17] += A[416]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[17] += A[417]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[17] += A[418]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[17] += A[419]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[17] += A[420]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[17] += A[421]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[17] += A[422]*acadoWorkspace.rk_dim24_bPerm[14];
acadoWorkspace.rk_dim24_bPerm[17] += A[423]*acadoWorkspace.rk_dim24_bPerm[15];
acadoWorkspace.rk_dim24_bPerm[17] += A[424]*acadoWorkspace.rk_dim24_bPerm[16];

acadoWorkspace.rk_dim24_bPerm[18] += A[432]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[18] += A[433]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[18] += A[434]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[18] += A[435]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[18] += A[436]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[18] += A[437]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[18] += A[438]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[18] += A[439]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[18] += A[440]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[18] += A[441]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[18] += A[442]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[18] += A[443]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[18] += A[444]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[18] += A[445]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[18] += A[446]*acadoWorkspace.rk_dim24_bPerm[14];
acadoWorkspace.rk_dim24_bPerm[18] += A[447]*acadoWorkspace.rk_dim24_bPerm[15];
acadoWorkspace.rk_dim24_bPerm[18] += A[448]*acadoWorkspace.rk_dim24_bPerm[16];
acadoWorkspace.rk_dim24_bPerm[18] += A[449]*acadoWorkspace.rk_dim24_bPerm[17];

acadoWorkspace.rk_dim24_bPerm[19] += A[456]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[19] += A[457]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[19] += A[458]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[19] += A[459]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[19] += A[460]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[19] += A[461]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[19] += A[462]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[19] += A[463]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[19] += A[464]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[19] += A[465]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[19] += A[466]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[19] += A[467]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[19] += A[468]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[19] += A[469]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[19] += A[470]*acadoWorkspace.rk_dim24_bPerm[14];
acadoWorkspace.rk_dim24_bPerm[19] += A[471]*acadoWorkspace.rk_dim24_bPerm[15];
acadoWorkspace.rk_dim24_bPerm[19] += A[472]*acadoWorkspace.rk_dim24_bPerm[16];
acadoWorkspace.rk_dim24_bPerm[19] += A[473]*acadoWorkspace.rk_dim24_bPerm[17];
acadoWorkspace.rk_dim24_bPerm[19] += A[474]*acadoWorkspace.rk_dim24_bPerm[18];

acadoWorkspace.rk_dim24_bPerm[20] += A[480]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[20] += A[481]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[20] += A[482]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[20] += A[483]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[20] += A[484]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[20] += A[485]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[20] += A[486]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[20] += A[487]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[20] += A[488]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[20] += A[489]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[20] += A[490]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[20] += A[491]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[20] += A[492]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[20] += A[493]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[20] += A[494]*acadoWorkspace.rk_dim24_bPerm[14];
acadoWorkspace.rk_dim24_bPerm[20] += A[495]*acadoWorkspace.rk_dim24_bPerm[15];
acadoWorkspace.rk_dim24_bPerm[20] += A[496]*acadoWorkspace.rk_dim24_bPerm[16];
acadoWorkspace.rk_dim24_bPerm[20] += A[497]*acadoWorkspace.rk_dim24_bPerm[17];
acadoWorkspace.rk_dim24_bPerm[20] += A[498]*acadoWorkspace.rk_dim24_bPerm[18];
acadoWorkspace.rk_dim24_bPerm[20] += A[499]*acadoWorkspace.rk_dim24_bPerm[19];

acadoWorkspace.rk_dim24_bPerm[21] += A[504]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[21] += A[505]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[21] += A[506]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[21] += A[507]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[21] += A[508]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[21] += A[509]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[21] += A[510]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[21] += A[511]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[21] += A[512]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[21] += A[513]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[21] += A[514]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[21] += A[515]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[21] += A[516]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[21] += A[517]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[21] += A[518]*acadoWorkspace.rk_dim24_bPerm[14];
acadoWorkspace.rk_dim24_bPerm[21] += A[519]*acadoWorkspace.rk_dim24_bPerm[15];
acadoWorkspace.rk_dim24_bPerm[21] += A[520]*acadoWorkspace.rk_dim24_bPerm[16];
acadoWorkspace.rk_dim24_bPerm[21] += A[521]*acadoWorkspace.rk_dim24_bPerm[17];
acadoWorkspace.rk_dim24_bPerm[21] += A[522]*acadoWorkspace.rk_dim24_bPerm[18];
acadoWorkspace.rk_dim24_bPerm[21] += A[523]*acadoWorkspace.rk_dim24_bPerm[19];
acadoWorkspace.rk_dim24_bPerm[21] += A[524]*acadoWorkspace.rk_dim24_bPerm[20];

acadoWorkspace.rk_dim24_bPerm[22] += A[528]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[22] += A[529]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[22] += A[530]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[22] += A[531]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[22] += A[532]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[22] += A[533]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[22] += A[534]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[22] += A[535]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[22] += A[536]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[22] += A[537]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[22] += A[538]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[22] += A[539]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[22] += A[540]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[22] += A[541]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[22] += A[542]*acadoWorkspace.rk_dim24_bPerm[14];
acadoWorkspace.rk_dim24_bPerm[22] += A[543]*acadoWorkspace.rk_dim24_bPerm[15];
acadoWorkspace.rk_dim24_bPerm[22] += A[544]*acadoWorkspace.rk_dim24_bPerm[16];
acadoWorkspace.rk_dim24_bPerm[22] += A[545]*acadoWorkspace.rk_dim24_bPerm[17];
acadoWorkspace.rk_dim24_bPerm[22] += A[546]*acadoWorkspace.rk_dim24_bPerm[18];
acadoWorkspace.rk_dim24_bPerm[22] += A[547]*acadoWorkspace.rk_dim24_bPerm[19];
acadoWorkspace.rk_dim24_bPerm[22] += A[548]*acadoWorkspace.rk_dim24_bPerm[20];
acadoWorkspace.rk_dim24_bPerm[22] += A[549]*acadoWorkspace.rk_dim24_bPerm[21];

acadoWorkspace.rk_dim24_bPerm[23] += A[552]*acadoWorkspace.rk_dim24_bPerm[0];
acadoWorkspace.rk_dim24_bPerm[23] += A[553]*acadoWorkspace.rk_dim24_bPerm[1];
acadoWorkspace.rk_dim24_bPerm[23] += A[554]*acadoWorkspace.rk_dim24_bPerm[2];
acadoWorkspace.rk_dim24_bPerm[23] += A[555]*acadoWorkspace.rk_dim24_bPerm[3];
acadoWorkspace.rk_dim24_bPerm[23] += A[556]*acadoWorkspace.rk_dim24_bPerm[4];
acadoWorkspace.rk_dim24_bPerm[23] += A[557]*acadoWorkspace.rk_dim24_bPerm[5];
acadoWorkspace.rk_dim24_bPerm[23] += A[558]*acadoWorkspace.rk_dim24_bPerm[6];
acadoWorkspace.rk_dim24_bPerm[23] += A[559]*acadoWorkspace.rk_dim24_bPerm[7];
acadoWorkspace.rk_dim24_bPerm[23] += A[560]*acadoWorkspace.rk_dim24_bPerm[8];
acadoWorkspace.rk_dim24_bPerm[23] += A[561]*acadoWorkspace.rk_dim24_bPerm[9];
acadoWorkspace.rk_dim24_bPerm[23] += A[562]*acadoWorkspace.rk_dim24_bPerm[10];
acadoWorkspace.rk_dim24_bPerm[23] += A[563]*acadoWorkspace.rk_dim24_bPerm[11];
acadoWorkspace.rk_dim24_bPerm[23] += A[564]*acadoWorkspace.rk_dim24_bPerm[12];
acadoWorkspace.rk_dim24_bPerm[23] += A[565]*acadoWorkspace.rk_dim24_bPerm[13];
acadoWorkspace.rk_dim24_bPerm[23] += A[566]*acadoWorkspace.rk_dim24_bPerm[14];
acadoWorkspace.rk_dim24_bPerm[23] += A[567]*acadoWorkspace.rk_dim24_bPerm[15];
acadoWorkspace.rk_dim24_bPerm[23] += A[568]*acadoWorkspace.rk_dim24_bPerm[16];
acadoWorkspace.rk_dim24_bPerm[23] += A[569]*acadoWorkspace.rk_dim24_bPerm[17];
acadoWorkspace.rk_dim24_bPerm[23] += A[570]*acadoWorkspace.rk_dim24_bPerm[18];
acadoWorkspace.rk_dim24_bPerm[23] += A[571]*acadoWorkspace.rk_dim24_bPerm[19];
acadoWorkspace.rk_dim24_bPerm[23] += A[572]*acadoWorkspace.rk_dim24_bPerm[20];
acadoWorkspace.rk_dim24_bPerm[23] += A[573]*acadoWorkspace.rk_dim24_bPerm[21];
acadoWorkspace.rk_dim24_bPerm[23] += A[574]*acadoWorkspace.rk_dim24_bPerm[22];


solve_dim24_triangular( A, acadoWorkspace.rk_dim24_bPerm );
b[0] = acadoWorkspace.rk_dim24_bPerm[0];
b[1] = acadoWorkspace.rk_dim24_bPerm[1];
b[2] = acadoWorkspace.rk_dim24_bPerm[2];
b[3] = acadoWorkspace.rk_dim24_bPerm[3];
b[4] = acadoWorkspace.rk_dim24_bPerm[4];
b[5] = acadoWorkspace.rk_dim24_bPerm[5];
b[6] = acadoWorkspace.rk_dim24_bPerm[6];
b[7] = acadoWorkspace.rk_dim24_bPerm[7];
b[8] = acadoWorkspace.rk_dim24_bPerm[8];
b[9] = acadoWorkspace.rk_dim24_bPerm[9];
b[10] = acadoWorkspace.rk_dim24_bPerm[10];
b[11] = acadoWorkspace.rk_dim24_bPerm[11];
b[12] = acadoWorkspace.rk_dim24_bPerm[12];
b[13] = acadoWorkspace.rk_dim24_bPerm[13];
b[14] = acadoWorkspace.rk_dim24_bPerm[14];
b[15] = acadoWorkspace.rk_dim24_bPerm[15];
b[16] = acadoWorkspace.rk_dim24_bPerm[16];
b[17] = acadoWorkspace.rk_dim24_bPerm[17];
b[18] = acadoWorkspace.rk_dim24_bPerm[18];
b[19] = acadoWorkspace.rk_dim24_bPerm[19];
b[20] = acadoWorkspace.rk_dim24_bPerm[20];
b[21] = acadoWorkspace.rk_dim24_bPerm[21];
b[22] = acadoWorkspace.rk_dim24_bPerm[22];
b[23] = acadoWorkspace.rk_dim24_bPerm[23];
}



/** Matrix of size: 2 x 2 (row major format) */
static const real_t Ah_mat[ 4 ] = 
{ 2.5000000000000001e-02, 5.3867513459481292e-02, 
-3.8675134594812867e-03, 2.5000000000000001e-02 };


/* Fixed step size:0.1 */
int integrate( real_t* const rk_eta, int resetIntegrator )
{
int error;

int i;
int j;
int k;
int run;
int run1;
int tmp_index1;
int tmp_index2;

real_t det;

acadoWorkspace.rk_ttt = 0.0000000000000000e+00;
acadoWorkspace.rk_xxx[12] = rk_eta[192];
acadoWorkspace.rk_xxx[13] = rk_eta[193];
acadoWorkspace.rk_xxx[14] = rk_eta[194];
acadoWorkspace.rk_xxx[15] = rk_eta[195];
acadoWorkspace.rk_xxx[16] = rk_eta[196];
acadoWorkspace.rk_xxx[17] = rk_eta[197];
acadoWorkspace.rk_xxx[18] = rk_eta[198];
acadoWorkspace.rk_xxx[19] = rk_eta[199];
acadoWorkspace.rk_xxx[20] = rk_eta[200];
acadoWorkspace.rk_xxx[21] = rk_eta[201];
acadoWorkspace.rk_xxx[22] = rk_eta[202];
acadoWorkspace.rk_xxx[23] = rk_eta[203];

for (run = 0; run < 1; ++run)
{
if( resetIntegrator ) {
for (i = 0; i < 1; ++i)
{
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 12; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
rhs_jac( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_diffsTemp2[ run1 * 180 ]) );
for (j = 0; j < 12; ++j)
{
tmp_index1 = (run1 * 12) + (j);
acadoWorkspace.rk_A[tmp_index1 * 24] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 1] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 1)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 2] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 2)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 3] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 3)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 4] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 4)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 5] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 5)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 6] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 7] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 7)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 8] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 8)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 9] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 9)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 10] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 10)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 11] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 11)];
if( 0 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 24) + (j)] -= 1.0000000000000000e+00;
acadoWorkspace.rk_A[tmp_index1 * 24 + 12] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 13] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 1)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 14] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 2)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 15] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 3)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 16] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 4)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 17] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 5)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 18] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 19] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 7)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 20] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 8)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 21] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 9)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 22] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 10)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 23] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 11)];
if( 1 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 24) + (j + 12)] -= 1.0000000000000000e+00;
}
rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
acadoWorkspace.rk_b[run1 * 12] = acadoWorkspace.rk_kkk[run1] - acadoWorkspace.rk_rhsTemp[0];
acadoWorkspace.rk_b[run1 * 12 + 1] = acadoWorkspace.rk_kkk[run1 + 2] - acadoWorkspace.rk_rhsTemp[1];
acadoWorkspace.rk_b[run1 * 12 + 2] = acadoWorkspace.rk_kkk[run1 + 4] - acadoWorkspace.rk_rhsTemp[2];
acadoWorkspace.rk_b[run1 * 12 + 3] = acadoWorkspace.rk_kkk[run1 + 6] - acadoWorkspace.rk_rhsTemp[3];
acadoWorkspace.rk_b[run1 * 12 + 4] = acadoWorkspace.rk_kkk[run1 + 8] - acadoWorkspace.rk_rhsTemp[4];
acadoWorkspace.rk_b[run1 * 12 + 5] = acadoWorkspace.rk_kkk[run1 + 10] - acadoWorkspace.rk_rhsTemp[5];
acadoWorkspace.rk_b[run1 * 12 + 6] = acadoWorkspace.rk_kkk[run1 + 12] - acadoWorkspace.rk_rhsTemp[6];
acadoWorkspace.rk_b[run1 * 12 + 7] = acadoWorkspace.rk_kkk[run1 + 14] - acadoWorkspace.rk_rhsTemp[7];
acadoWorkspace.rk_b[run1 * 12 + 8] = acadoWorkspace.rk_kkk[run1 + 16] - acadoWorkspace.rk_rhsTemp[8];
acadoWorkspace.rk_b[run1 * 12 + 9] = acadoWorkspace.rk_kkk[run1 + 18] - acadoWorkspace.rk_rhsTemp[9];
acadoWorkspace.rk_b[run1 * 12 + 10] = acadoWorkspace.rk_kkk[run1 + 20] - acadoWorkspace.rk_rhsTemp[10];
acadoWorkspace.rk_b[run1 * 12 + 11] = acadoWorkspace.rk_kkk[run1 + 22] - acadoWorkspace.rk_rhsTemp[11];
}
det = solve_dim24_system( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim24_perm );
for (j = 0; j < 2; ++j)
{
acadoWorkspace.rk_kkk[j] += acadoWorkspace.rk_b[j * 12];
acadoWorkspace.rk_kkk[j + 2] += acadoWorkspace.rk_b[j * 12 + 1];
acadoWorkspace.rk_kkk[j + 4] += acadoWorkspace.rk_b[j * 12 + 2];
acadoWorkspace.rk_kkk[j + 6] += acadoWorkspace.rk_b[j * 12 + 3];
acadoWorkspace.rk_kkk[j + 8] += acadoWorkspace.rk_b[j * 12 + 4];
acadoWorkspace.rk_kkk[j + 10] += acadoWorkspace.rk_b[j * 12 + 5];
acadoWorkspace.rk_kkk[j + 12] += acadoWorkspace.rk_b[j * 12 + 6];
acadoWorkspace.rk_kkk[j + 14] += acadoWorkspace.rk_b[j * 12 + 7];
acadoWorkspace.rk_kkk[j + 16] += acadoWorkspace.rk_b[j * 12 + 8];
acadoWorkspace.rk_kkk[j + 18] += acadoWorkspace.rk_b[j * 12 + 9];
acadoWorkspace.rk_kkk[j + 20] += acadoWorkspace.rk_b[j * 12 + 10];
acadoWorkspace.rk_kkk[j + 22] += acadoWorkspace.rk_b[j * 12 + 11];
}
}
}
for (i = 0; i < 5; ++i)
{
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 12; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
rhs( acadoWorkspace.rk_xxx, acadoWorkspace.rk_rhsTemp );
acadoWorkspace.rk_b[run1 * 12] = acadoWorkspace.rk_kkk[run1] - acadoWorkspace.rk_rhsTemp[0];
acadoWorkspace.rk_b[run1 * 12 + 1] = acadoWorkspace.rk_kkk[run1 + 2] - acadoWorkspace.rk_rhsTemp[1];
acadoWorkspace.rk_b[run1 * 12 + 2] = acadoWorkspace.rk_kkk[run1 + 4] - acadoWorkspace.rk_rhsTemp[2];
acadoWorkspace.rk_b[run1 * 12 + 3] = acadoWorkspace.rk_kkk[run1 + 6] - acadoWorkspace.rk_rhsTemp[3];
acadoWorkspace.rk_b[run1 * 12 + 4] = acadoWorkspace.rk_kkk[run1 + 8] - acadoWorkspace.rk_rhsTemp[4];
acadoWorkspace.rk_b[run1 * 12 + 5] = acadoWorkspace.rk_kkk[run1 + 10] - acadoWorkspace.rk_rhsTemp[5];
acadoWorkspace.rk_b[run1 * 12 + 6] = acadoWorkspace.rk_kkk[run1 + 12] - acadoWorkspace.rk_rhsTemp[6];
acadoWorkspace.rk_b[run1 * 12 + 7] = acadoWorkspace.rk_kkk[run1 + 14] - acadoWorkspace.rk_rhsTemp[7];
acadoWorkspace.rk_b[run1 * 12 + 8] = acadoWorkspace.rk_kkk[run1 + 16] - acadoWorkspace.rk_rhsTemp[8];
acadoWorkspace.rk_b[run1 * 12 + 9] = acadoWorkspace.rk_kkk[run1 + 18] - acadoWorkspace.rk_rhsTemp[9];
acadoWorkspace.rk_b[run1 * 12 + 10] = acadoWorkspace.rk_kkk[run1 + 20] - acadoWorkspace.rk_rhsTemp[10];
acadoWorkspace.rk_b[run1 * 12 + 11] = acadoWorkspace.rk_kkk[run1 + 22] - acadoWorkspace.rk_rhsTemp[11];
}
solve_dim24_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim24_perm );
for (j = 0; j < 2; ++j)
{
acadoWorkspace.rk_kkk[j] += acadoWorkspace.rk_b[j * 12];
acadoWorkspace.rk_kkk[j + 2] += acadoWorkspace.rk_b[j * 12 + 1];
acadoWorkspace.rk_kkk[j + 4] += acadoWorkspace.rk_b[j * 12 + 2];
acadoWorkspace.rk_kkk[j + 6] += acadoWorkspace.rk_b[j * 12 + 3];
acadoWorkspace.rk_kkk[j + 8] += acadoWorkspace.rk_b[j * 12 + 4];
acadoWorkspace.rk_kkk[j + 10] += acadoWorkspace.rk_b[j * 12 + 5];
acadoWorkspace.rk_kkk[j + 12] += acadoWorkspace.rk_b[j * 12 + 6];
acadoWorkspace.rk_kkk[j + 14] += acadoWorkspace.rk_b[j * 12 + 7];
acadoWorkspace.rk_kkk[j + 16] += acadoWorkspace.rk_b[j * 12 + 8];
acadoWorkspace.rk_kkk[j + 18] += acadoWorkspace.rk_b[j * 12 + 9];
acadoWorkspace.rk_kkk[j + 20] += acadoWorkspace.rk_b[j * 12 + 10];
acadoWorkspace.rk_kkk[j + 22] += acadoWorkspace.rk_b[j * 12 + 11];
}
}
for (run1 = 0; run1 < 2; ++run1)
{
for (j = 0; j < 12; ++j)
{
acadoWorkspace.rk_xxx[j] = rk_eta[j];
tmp_index1 = j;
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2]*acadoWorkspace.rk_kkk[tmp_index1 * 2];
acadoWorkspace.rk_xxx[j] += + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_kkk[tmp_index1 * 2 + 1];
}
rhs_jac( acadoWorkspace.rk_xxx, &(acadoWorkspace.rk_diffsTemp2[ run1 * 180 ]) );
for (j = 0; j < 12; ++j)
{
tmp_index1 = (run1 * 12) + (j);
acadoWorkspace.rk_A[tmp_index1 * 24] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 1] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 1)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 2] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 2)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 3] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 3)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 4] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 4)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 5] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 5)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 6] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 7] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 7)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 8] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 8)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 9] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 9)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 10] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 10)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 11] = + Ah_mat[run1 * 2]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 11)];
if( 0 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 24) + (j)] -= 1.0000000000000000e+00;
acadoWorkspace.rk_A[tmp_index1 * 24 + 12] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 13] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 1)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 14] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 2)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 15] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 3)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 16] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 4)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 17] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 5)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 18] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 6)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 19] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 7)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 20] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 8)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 21] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 9)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 22] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 10)];
acadoWorkspace.rk_A[tmp_index1 * 24 + 23] = + Ah_mat[run1 * 2 + 1]*acadoWorkspace.rk_diffsTemp2[(run1 * 180) + (j * 15 + 11)];
if( 1 == run1 ) acadoWorkspace.rk_A[(tmp_index1 * 24) + (j + 12)] -= 1.0000000000000000e+00;
}
}
for (run1 = 0; run1 < 12; ++run1)
{
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_b[i * 12] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1)];
acadoWorkspace.rk_b[i * 12 + 1] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 15)];
acadoWorkspace.rk_b[i * 12 + 2] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 30)];
acadoWorkspace.rk_b[i * 12 + 3] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 45)];
acadoWorkspace.rk_b[i * 12 + 4] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 60)];
acadoWorkspace.rk_b[i * 12 + 5] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 75)];
acadoWorkspace.rk_b[i * 12 + 6] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 90)];
acadoWorkspace.rk_b[i * 12 + 7] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 105)];
acadoWorkspace.rk_b[i * 12 + 8] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 120)];
acadoWorkspace.rk_b[i * 12 + 9] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 135)];
acadoWorkspace.rk_b[i * 12 + 10] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 150)];
acadoWorkspace.rk_b[i * 12 + 11] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (run1 + 165)];
}
if( 0 == run1 ) {
det = solve_dim24_system( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim24_perm );
}
 else {
solve_dim24_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim24_perm );
}
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffK[i] = acadoWorkspace.rk_b[i * 12];
acadoWorkspace.rk_diffK[i + 2] = acadoWorkspace.rk_b[i * 12 + 1];
acadoWorkspace.rk_diffK[i + 4] = acadoWorkspace.rk_b[i * 12 + 2];
acadoWorkspace.rk_diffK[i + 6] = acadoWorkspace.rk_b[i * 12 + 3];
acadoWorkspace.rk_diffK[i + 8] = acadoWorkspace.rk_b[i * 12 + 4];
acadoWorkspace.rk_diffK[i + 10] = acadoWorkspace.rk_b[i * 12 + 5];
acadoWorkspace.rk_diffK[i + 12] = acadoWorkspace.rk_b[i * 12 + 6];
acadoWorkspace.rk_diffK[i + 14] = acadoWorkspace.rk_b[i * 12 + 7];
acadoWorkspace.rk_diffK[i + 16] = acadoWorkspace.rk_b[i * 12 + 8];
acadoWorkspace.rk_diffK[i + 18] = acadoWorkspace.rk_b[i * 12 + 9];
acadoWorkspace.rk_diffK[i + 20] = acadoWorkspace.rk_b[i * 12 + 10];
acadoWorkspace.rk_diffK[i + 22] = acadoWorkspace.rk_b[i * 12 + 11];
}
for (i = 0; i < 12; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 15) + (run1)] = (i == run1-0);
acadoWorkspace.rk_diffsNew2[(i * 15) + (run1)] += + acadoWorkspace.rk_diffK[i * 2]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_diffK[i * 2 + 1]*(real_t)5.0000000000000003e-02;
}
}
for (run1 = 0; run1 < 3; ++run1)
{
for (i = 0; i < 2; ++i)
{
for (j = 0; j < 12; ++j)
{
tmp_index1 = (i * 12) + (j);
tmp_index2 = (run1) + (j * 15);
acadoWorkspace.rk_b[tmp_index1] = - acadoWorkspace.rk_diffsTemp2[(i * 180) + (tmp_index2 + 12)];
}
}
solve_dim24_system_reuse( acadoWorkspace.rk_A, acadoWorkspace.rk_b, acadoWorkspace.rk_dim24_perm );
for (i = 0; i < 2; ++i)
{
acadoWorkspace.rk_diffK[i] = acadoWorkspace.rk_b[i * 12];
acadoWorkspace.rk_diffK[i + 2] = acadoWorkspace.rk_b[i * 12 + 1];
acadoWorkspace.rk_diffK[i + 4] = acadoWorkspace.rk_b[i * 12 + 2];
acadoWorkspace.rk_diffK[i + 6] = acadoWorkspace.rk_b[i * 12 + 3];
acadoWorkspace.rk_diffK[i + 8] = acadoWorkspace.rk_b[i * 12 + 4];
acadoWorkspace.rk_diffK[i + 10] = acadoWorkspace.rk_b[i * 12 + 5];
acadoWorkspace.rk_diffK[i + 12] = acadoWorkspace.rk_b[i * 12 + 6];
acadoWorkspace.rk_diffK[i + 14] = acadoWorkspace.rk_b[i * 12 + 7];
acadoWorkspace.rk_diffK[i + 16] = acadoWorkspace.rk_b[i * 12 + 8];
acadoWorkspace.rk_diffK[i + 18] = acadoWorkspace.rk_b[i * 12 + 9];
acadoWorkspace.rk_diffK[i + 20] = acadoWorkspace.rk_b[i * 12 + 10];
acadoWorkspace.rk_diffK[i + 22] = acadoWorkspace.rk_b[i * 12 + 11];
}
for (i = 0; i < 12; ++i)
{
acadoWorkspace.rk_diffsNew2[(i * 15) + (run1 + 12)] = + acadoWorkspace.rk_diffK[i * 2]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_diffK[i * 2 + 1]*(real_t)5.0000000000000003e-02;
}
}
rk_eta[0] += + acadoWorkspace.rk_kkk[0]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[1]*(real_t)5.0000000000000003e-02;
rk_eta[1] += + acadoWorkspace.rk_kkk[2]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[3]*(real_t)5.0000000000000003e-02;
rk_eta[2] += + acadoWorkspace.rk_kkk[4]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[5]*(real_t)5.0000000000000003e-02;
rk_eta[3] += + acadoWorkspace.rk_kkk[6]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[7]*(real_t)5.0000000000000003e-02;
rk_eta[4] += + acadoWorkspace.rk_kkk[8]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[9]*(real_t)5.0000000000000003e-02;
rk_eta[5] += + acadoWorkspace.rk_kkk[10]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[11]*(real_t)5.0000000000000003e-02;
rk_eta[6] += + acadoWorkspace.rk_kkk[12]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[13]*(real_t)5.0000000000000003e-02;
rk_eta[7] += + acadoWorkspace.rk_kkk[14]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[15]*(real_t)5.0000000000000003e-02;
rk_eta[8] += + acadoWorkspace.rk_kkk[16]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[17]*(real_t)5.0000000000000003e-02;
rk_eta[9] += + acadoWorkspace.rk_kkk[18]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[19]*(real_t)5.0000000000000003e-02;
rk_eta[10] += + acadoWorkspace.rk_kkk[20]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[21]*(real_t)5.0000000000000003e-02;
rk_eta[11] += + acadoWorkspace.rk_kkk[22]*(real_t)5.0000000000000003e-02 + acadoWorkspace.rk_kkk[23]*(real_t)5.0000000000000003e-02;
for (i = 0; i < 12; ++i)
{
for (j = 0; j < 12; ++j)
{
tmp_index2 = (j) + (i * 12);
rk_eta[tmp_index2 + 12] = acadoWorkspace.rk_diffsNew2[(i * 15) + (j)];
}
for (j = 0; j < 3; ++j)
{
tmp_index2 = (j) + (i * 3);
rk_eta[tmp_index2 + 156] = acadoWorkspace.rk_diffsNew2[(i * 15) + (j + 12)];
}
}
resetIntegrator = 0;
acadoWorkspace.rk_ttt += 1.0000000000000000e+00;
}
for (i = 0; i < 12; ++i)
{
}
if( det < 1e-12 ) {
error = 2;
} else if( det < 1e-6 ) {
error = 1;
} else {
error = 0;
}
return error;
}



