function out = jac_sig_r_tl_cubic(r_n,r_e,r_d,v,gamma,xi,w_e,w_n,w_d,terr_dis,p1_n,p1_e,p1_h,p2_n,p2_e,p2_h,p3_n,p3_e,p3_h,r_offset,delta_r0,k_r,sig_r,d_occ,delta_r,vG_sq,vG,vG_n,vG_e,vG_d)
%JAC_SIG_R_TL_CUBIC
%    OUT = JAC_SIG_R_TL_CUBIC(R_N,R_E,R_D,V,GAMMA,XI,W_E,W_N,W_D,TERR_DIS,P1_N,P1_E,P1_H,P2_N,P2_E,P2_H,P3_N,P3_E,P3_H,R_OFFSET,DELTA_R0,K_R,SIG_R,D_OCC,DELTA_R,VG_SQ,VG,VG_N,VG_E,VG_D)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    11-Oct-2019 01:12:02

t2 = p1_h-p2_h;
t3 = -d_occ+delta_r+r_offset;
t4 = 1.0./delta_r.^3;
t5 = p2_h-p3_h;
t6 = terr_dis.^2;
t7 = t5.*terr_dis.*vG_e;
t8 = t2.*terr_dis.*vG_n;
t12 = t6.*vG_d;
t9 = t7+t8-t12;
t10 = 1.0./t9;
t11 = t3.^2;
t13 = cos(gamma);
t14 = sin(gamma);
t15 = cos(xi);
t16 = sin(xi);
t17 = t13.*t15.*vG_n.*2.0;
t18 = t13.*t16.*vG_e.*2.0;
t20 = t14.*vG_d.*2.0;
t19 = t17+t18-t20;
t21 = 1.0./vG;
t22 = t13.*v.*vG_d.*2.0;
t23 = t14.*t15.*v.*vG_n.*2.0;
t24 = t14.*t16.*v.*vG_e.*2.0;
t25 = t22+t23+t24;
t26 = p1_h+r_d;
t27 = t6.*t26;
t28 = p1_h.*t6;
t29 = p1_e-r_e;
t30 = t5.*t29.*terr_dis;
t31 = p1_n-r_n;
t32 = t2.*t31.*terr_dis;
t33 = t27+t28+t30+t32;
t34 = 1.0./delta_r;
t35 = t13.*t15.*v.*vG_e.*2.0;
t37 = t13.*t16.*v.*vG_n.*2.0;
t36 = t35-t37;
out = [t2.*t4.*t10.*t11.*terr_dis.*vG.*3.0,t4.*t5.*t10.*t11.*terr_dis.*vG.*3.0,t4.*t6.*t10.*t11.*vG.*-3.0,t4.*t11.*(k_r.*t19+d_occ.*t10.*(t6.*t14+t2.*t13.*t15.*terr_dis+t5.*t13.*t16.*terr_dis)-t10.*t19.*t21.*t33.*(1.0./2.0)).*3.0-k_r.*sig_r.*t19.*t34.*3.0,t4.*t11.*(k_r.*t25+d_occ.*t10.*(-t6.*t13.*v+t2.*t14.*t15.*terr_dis.*v+t5.*t14.*t16.*terr_dis.*v)-t10.*t21.*t25.*t33.*(1.0./2.0)).*-3.0+k_r.*sig_r.*t25.*t34.*3.0,t4.*t11.*(-k_r.*t36+d_occ.*t10.*(t2.*t13.*t16.*terr_dis.*v-t5.*t13.*t15.*terr_dis.*v)+t10.*t21.*t33.*t36.*(1.0./2.0)).*-3.0-k_r.*sig_r.*t34.*t36.*3.0];
